+ source ./common/disk_lib.sh
++ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment!'
+ message='Start to prepare the test environment!'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment!'
Thu Dec 29 18:04:02 2022 - INFO  - Start to prepare the test environment!
+ DNF_INSTALL lvm2
+ pkgs=lvm2
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs lvm2 --node 1 --tempfile ''
Thu Dec 29 18:04:12 2022 - INFO  - pkgs:(lvm2) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ check_free_disk
++ TEST_DISK
++ id=1
++ python3 /root/GitRepo/mugen-riscv/libs/locallibs/get_test_device.py --device disk --node 1
+ disks=
+ disk_list=($disks)
+ local_disk=
+ local_disk1=
+ local_disk2=
+ local_disk3=
++ cat /etc/os-release
++ grep VERSION_ID
++ awk -F = '{print$NF}'
++ awk -F '"' '{print$2}'
+ version_id=22.03
+ LOG_INFO 'End to prepare the test environment!'
+ message='End to prepare the test environment!'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment!'
Thu Dec 29 18:04:22 2022 - INFO  - End to prepare the test environment!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase!'
+ message='Start executing testcase!'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase!'
Thu Dec 29 18:04:23 2022 - INFO  - Start executing testcase!
+ pvcreate -y /dev/ /dev/
  No device found for /dev/.
  No device found for /dev/.
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvmove_001.sh line 31'
+ message='oe_test_lvm2_pvmove_001.sh line 31'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvmove_001.sh line 31'
Thu Dec 29 18:04:24 2022 - ERROR - oe_test_lvm2_pvmove_001.sh line 31
+ return 0
+ pvs
+ grep /dev/
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvmove_001.sh line 33'
+ message='oe_test_lvm2_pvmove_001.sh line 33'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvmove_001.sh line 33'
Thu Dec 29 18:04:25 2022 - ERROR - oe_test_lvm2_pvmove_001.sh line 33
+ return 0
+ vgcreate test /dev/ /dev/
  No device found for /dev/.
  No device found for /dev/.
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvmove_001.sh line 35'
+ message='oe_test_lvm2_pvmove_001.sh line 35'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvmove_001.sh line 35'
Thu Dec 29 18:04:26 2022 - ERROR - oe_test_lvm2_pvmove_001.sh line 35
+ return 0
+ lvcreate -L 50MB -n lv1 test
+ grep 'Logical volume "lv1" created'
  /dev/mapper/control: open failed: No such device
  Failure to communicate with kernel device-mapper driver.
  Check that device-mapper is available in the kernel.
  Incompatible libdevmapper 1.02.181 (2021-10-20) and kernel driver (unknown version).
  striped: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvmove_001.sh line 37'
+ message='oe_test_lvm2_pvmove_001.sh line 37'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvmove_001.sh line 37'
Thu Dec 29 18:04:27 2022 - ERROR - oe_test_lvm2_pvmove_001.sh line 37
+ return 0
+ pvmove -q
  /dev/mapper/control: open failed: No such device
  Failure to communicate with kernel device-mapper driver.
  Check that device-mapper is available in the kernel.
  Incompatible libdevmapper 1.02.181 (2021-10-20) and kernel driver (unknown version).
modprobe: FATAL: Module dm-mirror not found in directory /lib/modules/5.10.0-9.oe2203.riscv64
  /usr/sbin/modprobe failed: 1
  Required device-mapper target(s) not detected in your kernel.
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvmove_001.sh line 39'
+ message='oe_test_lvm2_pvmove_001.sh line 39'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvmove_001.sh line 39'
Thu Dec 29 18:04:28 2022 - ERROR - oe_test_lvm2_pvmove_001.sh line 39
+ return 0
+ pvmove -t
+ grep 'TEST MODE: Metadata will NOT be updated and volumes will not be (de)activated'
  TEST MODE: Metadata will NOT be updated and volumes will not be (de)activated.
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ '[22.03' = '22.03]'
oe_test_lvm2_pvmove_001.sh: line 42: [22.03: command not found
+ touch /etc/lvm/profile/my.profile
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ pvmove --commandprofile my /dev/
  /dev/mapper/control: open failed: No such device
  Failure to communicate with kernel device-mapper driver.
  Check that device-mapper is available in the kernel.
  Incompatible libdevmapper 1.02.181 (2021-10-20) and kernel driver (unknown version).
modprobe: FATAL: Module dm-mirror not found in directory /lib/modules/5.10.0-9.oe2203.riscv64
  /usr/sbin/modprobe failed: 1
  Required device-mapper target(s) not detected in your kernel.
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvmove_001.sh line 49'
+ message='oe_test_lvm2_pvmove_001.sh line 49'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvmove_001.sh line 49'
Thu Dec 29 18:04:30 2022 - ERROR - oe_test_lvm2_pvmove_001.sh line 49
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ pvmove --driverloaded y /dev/ /dev/
+ grep 'Moved: 100.00%'
  /dev/mapper/control: open failed: No such device
  Failure to communicate with kernel device-mapper driver.
  Check that device-mapper is available in the kernel.
  Incompatible libdevmapper 1.02.181 (2021-10-20) and kernel driver (unknown version).
modprobe: FATAL: Module dm-mirror not found in directory /lib/modules/5.10.0-9.oe2203.riscv64
  /usr/sbin/modprobe failed: 1
  Required device-mapper target(s) not detected in your kernel.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvmove_001.sh line 52'
+ message='oe_test_lvm2_pvmove_001.sh line 52'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvmove_001.sh line 52'
Thu Dec 29 18:04:37 2022 - ERROR - oe_test_lvm2_pvmove_001.sh line 52
+ return 0
+ grep 'Moved: 100.00%'
+ pvmove --nolocking /dev/ /dev/
  WARNING: File locking is disabled.
  /dev/mapper/control: open failed: No such device
  Failure to communicate with kernel device-mapper driver.
  Check that device-mapper is available in the kernel.
  Incompatible libdevmapper 1.02.181 (2021-10-20) and kernel driver (unknown version).
modprobe: FATAL: Module dm-mirror not found in directory /lib/modules/5.10.0-9.oe2203.riscv64
  /usr/sbin/modprobe failed: 1
  Required device-mapper target(s) not detected in your kernel.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvmove_001.sh line 54'
+ message='oe_test_lvm2_pvmove_001.sh line 54'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvmove_001.sh line 54'
Thu Dec 29 18:04:38 2022 - ERROR - oe_test_lvm2_pvmove_001.sh line 54
+ return 0
+ pvmove --lockopt /dev/ /dev/
+ grep 'Moved: 100.00%'
  /dev/mapper/control: open failed: No such device
  Failure to communicate with kernel device-mapper driver.
  Check that device-mapper is available in the kernel.
  Incompatible libdevmapper 1.02.181 (2021-10-20) and kernel driver (unknown version).
modprobe: FATAL: Module dm-mirror not found in directory /lib/modules/5.10.0-9.oe2203.riscv64
  /usr/sbin/modprobe failed: 1
  Required device-mapper target(s) not detected in your kernel.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvmove_001.sh line 56'
+ message='oe_test_lvm2_pvmove_001.sh line 56'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvmove_001.sh line 56'
Thu Dec 29 18:04:39 2022 - ERROR - oe_test_lvm2_pvmove_001.sh line 56
+ return 0
+ '[22.03' = '22.03]'
oe_test_lvm2_pvmove_001.sh: line 57: [22.03: command not found
+ LOG_INFO 'End executing testcase!'
+ message='End executing testcase!'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End executing testcase!'
Thu Dec 29 18:04:40 2022 - INFO  - End executing testcase!
+ CASE_RESULT 0
+ case_re=0
+ test -z 9
+ test 9 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Dec 29 18:04:41 2022 - ERROR - failed to execute the case.
+ exit 9
+ post_test
+ LOG_INFO 'Start environment cleanup.'
+ message='Start environment cleanup.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environment cleanup.'
Thu Dec 29 18:04:42 2022 - INFO  - Start environment cleanup.
+ vgremove -f test
  Volume group "test" not found
  Cannot process volume group test
+ pvremove -f /dev/
  No device found for /dev/.
+ pvremove -f /dev/
  No device found for /dev/.
+ rm -rf /etc/lvm/profile/my.profile
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Thu Dec 29 18:04:44 2022 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'Finish environment cleanup.'
+ message='Finish environment cleanup.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Thu Dec 29 18:04:45 2022 - INFO  - Finish environment cleanup.
