+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment'
+ message='Start to prepare the test environment'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment'
Tue Nov 21 22:47:25 2023 - INFO  - Start to prepare the test environment
+ DNF_INSTALL pylint
+ pkgs=pylint
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs pylint --node 1 --tempfile ''
+ tmpfile2=/tmp/tmp3gcajp5h
+ '[' -z '' ']'
+ tmpfile=/tmp/tmp3gcajp5h
+ LOG_INFO 'End to prepare the test environment'
+ message='End to prepare the test environment'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment'
Tue Nov 21 22:48:07 2023 - INFO  - End to prepare the test environment
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Nov 21 22:48:08 2023 - INFO  - Start to run test.
+ pylint --list-msgs
+ grep :blacklisted-name
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L31: pylint --list-msgs No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L31: pylint --list-msgs No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L31: pylint --list-msgs No Pass'
+ LOG_ERROR 'L31: pylint --list-msgs No Pass'
+ message='L31: pylint --list-msgs No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L31: pylint --list-msgs No Pass'
Tue Nov 21 22:48:14 2023 - ERROR - L31: pylint --list-msgs No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_03.sh line 31'
+ message='oe_test_pylint_03.sh line 31'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_03.sh line 31'
Tue Nov 21 22:48:14 2023 - ERROR - oe_test_pylint_03.sh line 31
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint --list-msgs-enabled
+ grep 'Enabled messages:'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L33: pylint --list-msgs-enabled No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L33: pylint --list-msgs-enabled No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L33: pylint --list-msgs-enabled No Pass'
+ LOG_ERROR 'L33: pylint --list-msgs-enabled No Pass'
+ message='L33: pylint --list-msgs-enabled No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L33: pylint --list-msgs-enabled No Pass'
Tue Nov 21 22:48:21 2023 - ERROR - L33: pylint --list-msgs-enabled No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_03.sh line 33'
+ message='oe_test_pylint_03.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_03.sh line 33'
Tue Nov 21 22:48:22 2023 - ERROR - oe_test_pylint_03.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint --list-groups
+ grep async
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L35: pylint --list-groups No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L35: pylint --list-groups No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L35: pylint --list-groups No Pass'
+ LOG_ERROR 'L35: pylint --list-groups No Pass'
+ message='L35: pylint --list-groups No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L35: pylint --list-groups No Pass'
Tue Nov 21 22:48:28 2023 - ERROR - L35: pylint --list-groups No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_03.sh line 35'
+ message='oe_test_pylint_03.sh line 35'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_03.sh line 35'
Tue Nov 21 22:48:28 2023 - ERROR - oe_test_pylint_03.sh line 35
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint --list-conf-levels
+ grep HIGH
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L37: pylint --list-conf-levels No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L37: pylint --list-conf-levels No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L37: pylint --list-conf-levels No Pass'
+ LOG_ERROR 'L37: pylint --list-conf-levels No Pass'
+ message='L37: pylint --list-conf-levels No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L37: pylint --list-conf-levels No Pass'
Tue Nov 21 22:48:35 2023 - ERROR - L37: pylint --list-conf-levels No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_03.sh line 37'
+ message='oe_test_pylint_03.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_03.sh line 37'
Tue Nov 21 22:48:35 2023 - ERROR - oe_test_pylint_03.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint --list-extensions
+ grep pylint.extensions.docstyle
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L39: pylint --list-extensions No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L39: pylint --list-extensions No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L39: pylint --list-extensions No Pass'
+ LOG_ERROR 'L39: pylint --list-extensions No Pass'
+ message='L39: pylint --list-extensions No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L39: pylint --list-extensions No Pass'
Tue Nov 21 22:48:41 2023 - ERROR - L39: pylint --list-extensions No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_03.sh line 39'
+ message='oe_test_pylint_03.sh line 39'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_03.sh line 39'
Tue Nov 21 22:48:42 2023 - ERROR - oe_test_pylint_03.sh line 39
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint --full-documentation
+ grep 'Pylint global options and switches'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L41: pylint --full-documentation No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L41: pylint --full-documentation No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L41: pylint --full-documentation No Pass'
+ LOG_ERROR 'L41: pylint --full-documentation No Pass'
+ message='L41: pylint --full-documentation No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L41: pylint --full-documentation No Pass'
Tue Nov 21 22:48:48 2023 - ERROR - L41: pylint --full-documentation No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_03.sh line 41'
+ message='oe_test_pylint_03.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_03.sh line 41'
Tue Nov 21 22:48:49 2023 - ERROR - oe_test_pylint_03.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint --generate-rcfile
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ grep pylint.conf
+ find . -name pylint.conf
./pylint.conf
+ CHECK_RESULT 0 0 0 'L44: pylint --generate-rcfile No Pass'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='L44: pylint --generate-rcfile No Pass'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ pylint --confidence=INFERENCE_FAILURE ./common/test.py
+ grep 'Your code has been rated at'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L46: pylint --confidence <levels> No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L46: pylint --confidence <levels> No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L46: pylint --confidence <levels> No Pass'
+ LOG_ERROR 'L46: pylint --confidence <levels> No Pass'
+ message='L46: pylint --confidence <levels> No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L46: pylint --confidence <levels> No Pass'
Tue Nov 21 22:49:03 2023 - ERROR - L46: pylint --confidence <levels> No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_03.sh line 46'
+ message='oe_test_pylint_03.sh line 46'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_03.sh line 46'
Tue Nov 21 22:49:04 2023 - ERROR - oe_test_pylint_03.sh line 46
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint -e C0103 ./common/test.py
+ grep 'Module test'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L48: pylint -e <msg ids> No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L48: pylint -e <msg ids> No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L48: pylint -e <msg ids> No Pass'
+ LOG_ERROR 'L48: pylint -e <msg ids> No Pass'
+ message='L48: pylint -e <msg ids> No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L48: pylint -e <msg ids> No Pass'
Tue Nov 21 22:49:12 2023 - ERROR - L48: pylint -e <msg ids> No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_03.sh line 48'
+ message='oe_test_pylint_03.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_03.sh line 48'
Tue Nov 21 22:49:12 2023 - ERROR - oe_test_pylint_03.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint --enable=C0103 ./common/test.py
+ grep 'Module test'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L50: pylint --enable <msg ids> No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L50: pylint --enable <msg ids> No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L50: pylint --enable <msg ids> No Pass'
+ LOG_ERROR 'L50: pylint --enable <msg ids> No Pass'
+ message='L50: pylint --enable <msg ids> No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L50: pylint --enable <msg ids> No Pass'
Tue Nov 21 22:49:19 2023 - ERROR - L50: pylint --enable <msg ids> No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_03.sh line 50'
+ message='oe_test_pylint_03.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_03.sh line 50'
Tue Nov 21 22:49:19 2023 - ERROR - oe_test_pylint_03.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Nov 21 22:49:20 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 9
+ test 9 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Nov 21 22:49:20 2023 - ERROR - failed to execute the case.
+ exit 9
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Nov 21 22:49:21 2023 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmp3gcajp5h ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmp3gcajp5h
+ '[' 0 -ne 0 ']'
+ rm -f pylint.conf
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Nov 21 22:49:33 2023 - INFO  - End to restore the test environment.
