+ source ../common/common.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Tue Nov 21 18:49:02 2023 - INFO  - Start to prepare the test environment.
+ common_pre
+ pip install -r ../common/requirements.txt
+ DNF_INSTALL 'nototools harfbuzz-devel cpio pango python3-gobject python3-cairo'
+ pkgs='nototools harfbuzz-devel cpio pango python3-gobject python3-cairo'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'nototools harfbuzz-devel cpio pango python3-gobject python3-cairo' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpo86vj2o4
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpo86vj2o4
+ notoconfig_pre
++ mktemp -d -t nototools.SRC.XXXXXXXXXXXX
+ TMP_SRCDIR=/tmp/nototools.SRC.y0sdIVYGuKDN
+ yumdownloader --source nototools --destdir /tmp/nototools.SRC.y0sdIVYGuKDN
No package nototools-0.2.17-1.oe2303.src available.
Exiting due to strict setting.
Error: No package nototools-0.2.17-1.oe2303.src available.
+ rpm2cpio '/tmp/nototools.SRC.y0sdIVYGuKDN/*.rpm'
+ cpio -div -D /tmp/nototools.SRC.y0sdIVYGuKDN
rpm2cpio: /tmp/nototools.SRC.y0sdIVYGuKDN/*.rpm: No such file or directory
+ tar -zxf '/tmp/nototools.SRC.y0sdIVYGuKDN/*.tar.gz' --strip-components 1 --directory /tmp/nototools.SRC.y0sdIVYGuKDN
tar (child): /tmp/nototools.SRC.y0sdIVYGuKDN/*.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
+ echo noto_tools=/tmp/nototools.SRC.y0sdIVYGuKDN
+ for src in "fonts" "cjk" "emoji"
+ echo noto_fonts=/tmp/nototools.SRC.y0sdIVYGuKDN/noto-fonts
+ for src in "fonts" "cjk" "emoji"
+ echo noto_cjk=/tmp/nototools.SRC.y0sdIVYGuKDN/noto-cjk
+ for src in "fonts" "cjk" "emoji"
+ echo noto_emoji=/tmp/nototools.SRC.y0sdIVYGuKDN/noto-emoji
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Tue Nov 21 18:55:30 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Nov 21 18:55:30 2023 - INFO  - Start to run test.
+ LOG_INFO 'generate_website_2_data help information '
+ message='generate_website_2_data help information '
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'generate_website_2_data help information '
Tue Nov 21 18:55:31 2023 - INFO  - generate_website_2_data help information 
+ generate_website_2_data.py -h
+ grep -q usage
Traceback (most recent call last):
  File "/usr/bin/generate_website_2_data.py", line 38, in <module>
    from nototools import create_image
  File "/usr/lib/python3.10/site-packages/nototools/create_image.py", line 32, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: -h error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: -h error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: -h error'
+ LOG_ERROR 'option: -h error'
+ message='option: -h error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: -h error'
Tue Nov 21 18:55:33 2023 - ERROR - option: -h error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_generate_website_2_data.sh line 39'
+ message='oe_test_nototools_base_generate_website_2_data.sh line 39'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_generate_website_2_data.sh line 39'
Tue Nov 21 18:55:33 2023 - ERROR - oe_test_nototools_base_generate_website_2_data.sh line 39
+ '[' 0 -eq 1 ']'
+ return 0
+ generate_website_2_data.py --help
+ grep -q usage
Traceback (most recent call last):
  File "/usr/bin/generate_website_2_data.py", line 38, in <module>
    from nototools import create_image
  File "/usr/lib/python3.10/site-packages/nototools/create_image.py", line 32, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --help error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --help error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --help error'
+ LOG_ERROR 'option: --help error'
+ message='option: --help error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --help error'
Tue Nov 21 18:55:35 2023 - ERROR - option: --help error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_generate_website_2_data.sh line 41'
+ message='oe_test_nototools_base_generate_website_2_data.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_generate_website_2_data.sh line 41'
Tue Nov 21 18:55:36 2023 - ERROR - oe_test_nototools_base_generate_website_2_data.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ generate_website_2_data.py -c
Traceback (most recent call last):
  File "/usr/bin/generate_website_2_data.py", line 38, in <module>
    from nototools import create_image
  File "/usr/lib/python3.10/site-packages/nototools/create_image.py", line 32, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: -c error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: -c error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: -c error'
+ LOG_ERROR 'option: -c error'
+ message='option: -c error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: -c error'
Tue Nov 21 18:55:38 2023 - ERROR - option: -c error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_generate_website_2_data.sh line 45'
+ message='oe_test_nototools_base_generate_website_2_data.sh line 45'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_generate_website_2_data.sh line 45'
Tue Nov 21 18:55:38 2023 - ERROR - oe_test_nototools_base_generate_website_2_data.sh line 45
+ '[' 0 -eq 1 ']'
+ return 0
+ generate_website_2_data.py --clean
Traceback (most recent call last):
  File "/usr/bin/generate_website_2_data.py", line 38, in <module>
    from nototools import create_image
  File "/usr/lib/python3.10/site-packages/nototools/create_image.py", line 32, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --clean error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --clean error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --clean error'
+ LOG_ERROR 'option: --clean error'
+ message='option: --clean error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --clean error'
Tue Nov 21 18:55:40 2023 - ERROR - option: --clean error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_generate_website_2_data.sh line 47'
+ message='oe_test_nototools_base_generate_website_2_data.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_generate_website_2_data.sh line 47'
Tue Nov 21 18:55:41 2023 - ERROR - oe_test_nototools_base_generate_website_2_data.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ generate_website_2_data.py -d
Traceback (most recent call last):
  File "/usr/bin/generate_website_2_data.py", line 38, in <module>
    from nototools import create_image
  File "/usr/lib/python3.10/site-packages/nototools/create_image.py", line 32, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: -d error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: -d error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: -d error'
+ LOG_ERROR 'option: -d error'
+ message='option: -d error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: -d error'
Tue Nov 21 18:55:43 2023 - ERROR - option: -d error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_generate_website_2_data.sh line 51'
+ message='oe_test_nototools_base_generate_website_2_data.sh line 51'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_generate_website_2_data.sh line 51'
Tue Nov 21 18:55:43 2023 - ERROR - oe_test_nototools_base_generate_website_2_data.sh line 51
+ '[' 0 -eq 1 ']'
+ return 0
+ generate_website_2_data.py --dest
Traceback (most recent call last):
  File "/usr/bin/generate_website_2_data.py", line 38, in <module>
    from nototools import create_image
  File "/usr/lib/python3.10/site-packages/nototools/create_image.py", line 32, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --dest error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --dest error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --dest error'
+ LOG_ERROR 'option: --dest error'
+ message='option: --dest error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --dest error'
Tue Nov 21 18:55:45 2023 - ERROR - option: --dest error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_generate_website_2_data.sh line 53'
+ message='oe_test_nototools_base_generate_website_2_data.sh line 53'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_generate_website_2_data.sh line 53'
Tue Nov 21 18:55:46 2023 - ERROR - oe_test_nototools_base_generate_website_2_data.sh line 53
+ '[' 0 -eq 1 ']'
+ return 0
+ generate_website_2_data.py -pj
Traceback (most recent call last):
  File "/usr/bin/generate_website_2_data.py", line 38, in <module>
    from nototools import create_image
  File "/usr/lib/python3.10/site-packages/nototools/create_image.py", line 32, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: -pj error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: -pj error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: -pj error'
+ LOG_ERROR 'option: -pj error'
+ message='option: -pj error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: -pj error'
Tue Nov 21 18:55:48 2023 - ERROR - option: -pj error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_generate_website_2_data.sh line 57'
+ message='oe_test_nototools_base_generate_website_2_data.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_generate_website_2_data.sh line 57'
Tue Nov 21 18:55:48 2023 - ERROR - oe_test_nototools_base_generate_website_2_data.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ generate_website_2_data.py --pretty_json
Traceback (most recent call last):
  File "/usr/bin/generate_website_2_data.py", line 38, in <module>
    from nototools import create_image
  File "/usr/lib/python3.10/site-packages/nototools/create_image.py", line 32, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --pretty_json error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --pretty_json error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --pretty_json error'
+ LOG_ERROR 'option: --pretty_json error'
+ message='option: --pretty_json error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --pretty_json error'
Tue Nov 21 18:55:50 2023 - ERROR - option: --pretty_json error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_generate_website_2_data.sh line 59'
+ message='oe_test_nototools_base_generate_website_2_data.sh line 59'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_generate_website_2_data.sh line 59'
Tue Nov 21 18:55:51 2023 - ERROR - oe_test_nototools_base_generate_website_2_data.sh line 59
+ '[' 0 -eq 1 ']'
+ return 0
+ generate_website_2_data.py -nr
Traceback (most recent call last):
  File "/usr/bin/generate_website_2_data.py", line 38, in <module>
    from nototools import create_image
  File "/usr/lib/python3.10/site-packages/nototools/create_image.py", line 32, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: -nr error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: -nr error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: -nr error'
+ LOG_ERROR 'option: -nr error'
+ message='option: -nr error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: -nr error'
Tue Nov 21 18:55:53 2023 - ERROR - option: -nr error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_generate_website_2_data.sh line 63'
+ message='oe_test_nototools_base_generate_website_2_data.sh line 63'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_generate_website_2_data.sh line 63'
Tue Nov 21 18:55:53 2023 - ERROR - oe_test_nototools_base_generate_website_2_data.sh line 63
+ '[' 0 -eq 1 ']'
+ return 0
+ generate_website_2_data.py --no_repo_check
Traceback (most recent call last):
  File "/usr/bin/generate_website_2_data.py", line 38, in <module>
    from nototools import create_image
  File "/usr/lib/python3.10/site-packages/nototools/create_image.py", line 32, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --no_repo_check error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --no_repo_check error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --no_repo_check error'
+ LOG_ERROR 'option: --no_repo_check error'
+ message='option: --no_repo_check error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --no_repo_check error'
Tue Nov 21 18:55:55 2023 - ERROR - option: --no_repo_check error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_generate_website_2_data.sh line 65'
+ message='oe_test_nototools_base_generate_website_2_data.sh line 65'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_generate_website_2_data.sh line 65'
Tue Nov 21 18:55:56 2023 - ERROR - oe_test_nototools_base_generate_website_2_data.sh line 65
+ '[' 0 -eq 1 ']'
+ return 0
+ generate_website_2_data.py -nz
Traceback (most recent call last):
  File "/usr/bin/generate_website_2_data.py", line 38, in <module>
    from nototools import create_image
  File "/usr/lib/python3.10/site-packages/nototools/create_image.py", line 32, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: -nz error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: -nz error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: -nz error'
+ LOG_ERROR 'option: -nz error'
+ message='option: -nz error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: -nz error'
Tue Nov 21 18:55:58 2023 - ERROR - option: -nz error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_generate_website_2_data.sh line 69'
+ message='oe_test_nototools_base_generate_website_2_data.sh line 69'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_generate_website_2_data.sh line 69'
Tue Nov 21 18:55:58 2023 - ERROR - oe_test_nototools_base_generate_website_2_data.sh line 69
+ '[' 0 -eq 1 ']'
+ return 0
+ generate_website_2_data.py --no_zips
Traceback (most recent call last):
  File "/usr/bin/generate_website_2_data.py", line 38, in <module>
    from nototools import create_image
  File "/usr/lib/python3.10/site-packages/nototools/create_image.py", line 32, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --no_zips error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --no_zips error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --no_zips error'
+ LOG_ERROR 'option: --no_zips error'
+ message='option: --no_zips error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --no_zips error'
Tue Nov 21 18:56:00 2023 - ERROR - option: --no_zips error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_generate_website_2_data.sh line 71'
+ message='oe_test_nototools_base_generate_website_2_data.sh line 71'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_generate_website_2_data.sh line 71'
Tue Nov 21 18:56:01 2023 - ERROR - oe_test_nototools_base_generate_website_2_data.sh line 71
+ '[' 0 -eq 1 ']'
+ return 0
+ generate_website_2_data.py -ni
Traceback (most recent call last):
  File "/usr/bin/generate_website_2_data.py", line 38, in <module>
    from nototools import create_image
  File "/usr/lib/python3.10/site-packages/nototools/create_image.py", line 32, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: -ni error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: -ni error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: -ni error'
+ LOG_ERROR 'option: -ni error'
+ message='option: -ni error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: -ni error'
Tue Nov 21 18:56:03 2023 - ERROR - option: -ni error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_generate_website_2_data.sh line 75'
+ message='oe_test_nototools_base_generate_website_2_data.sh line 75'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_generate_website_2_data.sh line 75'
Tue Nov 21 18:56:03 2023 - ERROR - oe_test_nototools_base_generate_website_2_data.sh line 75
+ '[' 0 -eq 1 ']'
+ return 0
+ generate_website_2_data.py --no_images
Traceback (most recent call last):
  File "/usr/bin/generate_website_2_data.py", line 38, in <module>
    from nototools import create_image
  File "/usr/lib/python3.10/site-packages/nototools/create_image.py", line 32, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --no_images error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --no_images error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --no_images error'
+ LOG_ERROR 'option: --no_images error'
+ message='option: --no_images error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --no_images error'
Tue Nov 21 18:56:05 2023 - ERROR - option: --no_images error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_generate_website_2_data.sh line 77'
+ message='oe_test_nototools_base_generate_website_2_data.sh line 77'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_generate_website_2_data.sh line 77'
Tue Nov 21 18:56:06 2023 - ERROR - oe_test_nototools_base_generate_website_2_data.sh line 77
+ '[' 0 -eq 1 ']'
+ return 0
+ generate_website_2_data -nd
oe_test_nototools_base_generate_website_2_data.sh: line 80: generate_website_2_data: command not found
+ CHECK_RESULT 127 0 0 'option: -nd error'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='option: -nd error'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'option: -nd error'
+ LOG_ERROR 'option: -nd error'
+ message='option: -nd error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: -nd error'
Tue Nov 21 18:56:06 2023 - ERROR - option: -nd error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_generate_website_2_data.sh line 81'
+ message='oe_test_nototools_base_generate_website_2_data.sh line 81'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_generate_website_2_data.sh line 81'
Tue Nov 21 18:56:07 2023 - ERROR - oe_test_nototools_base_generate_website_2_data.sh line 81
+ '[' 0 -eq 1 ']'
+ return 0
+ generate_website_2_data --no_data
oe_test_nototools_base_generate_website_2_data.sh: line 82: generate_website_2_data: command not found
+ CHECK_RESULT 127 0 0 'option: --no_data error'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='option: --no_data error'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'option: --no_data error'
+ LOG_ERROR 'option: --no_data error'
+ message='option: --no_data error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --no_data error'
Tue Nov 21 18:56:07 2023 - ERROR - option: --no_data error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_generate_website_2_data.sh line 83'
+ message='oe_test_nototools_base_generate_website_2_data.sh line 83'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_generate_website_2_data.sh line 83'
Tue Nov 21 18:56:08 2023 - ERROR - oe_test_nototools_base_generate_website_2_data.sh line 83
+ '[' 0 -eq 1 ']'
+ return 0
+ generate_website_2_data.py -nc
Traceback (most recent call last):
  File "/usr/bin/generate_website_2_data.py", line 38, in <module>
    from nototools import create_image
  File "/usr/lib/python3.10/site-packages/nototools/create_image.py", line 32, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: -nc error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: -nc error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: -nc error'
+ LOG_ERROR 'option: -nc error'
+ message='option: -nc error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: -nc error'
Tue Nov 21 18:56:10 2023 - ERROR - option: -nc error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_generate_website_2_data.sh line 87'
+ message='oe_test_nototools_base_generate_website_2_data.sh line 87'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_generate_website_2_data.sh line 87'
Tue Nov 21 18:56:10 2023 - ERROR - oe_test_nototools_base_generate_website_2_data.sh line 87
+ '[' 0 -eq 1 ']'
+ return 0
+ generate_website_2_data.py --no_css
Traceback (most recent call last):
  File "/usr/bin/generate_website_2_data.py", line 38, in <module>
    from nototools import create_image
  File "/usr/lib/python3.10/site-packages/nototools/create_image.py", line 32, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --no_css error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --no_css error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --no_css error'
+ LOG_ERROR 'option: --no_css error'
+ message='option: --no_css error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --no_css error'
Tue Nov 21 18:56:12 2023 - ERROR - option: --no_css error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_generate_website_2_data.sh line 89'
+ message='oe_test_nototools_base_generate_website_2_data.sh line 89'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_generate_website_2_data.sh line 89'
Tue Nov 21 18:56:13 2023 - ERROR - oe_test_nototools_base_generate_website_2_data.sh line 89
+ '[' 0 -eq 1 ']'
+ return 0
+ generate_website_2_data.py -n
Traceback (most recent call last):
  File "/usr/bin/generate_website_2_data.py", line 38, in <module>
    from nototools import create_image
  File "/usr/lib/python3.10/site-packages/nototools/create_image.py", line 32, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: -n error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: -n error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: -n error'
+ LOG_ERROR 'option: -n error'
+ message='option: -n error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: -n error'
Tue Nov 21 18:56:15 2023 - ERROR - option: -n error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_generate_website_2_data.sh line 93'
+ message='oe_test_nototools_base_generate_website_2_data.sh line 93'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_generate_website_2_data.sh line 93'
Tue Nov 21 18:56:15 2023 - ERROR - oe_test_nototools_base_generate_website_2_data.sh line 93
+ '[' 0 -eq 1 ']'
+ return 0
+ generate_website_2_data.py --no_build
Traceback (most recent call last):
  File "/usr/bin/generate_website_2_data.py", line 38, in <module>
    from nototools import create_image
  File "/usr/lib/python3.10/site-packages/nototools/create_image.py", line 32, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --no_build error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --no_build error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --no_build error'
+ LOG_ERROR 'option: --no_build error'
+ message='option: --no_build error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --no_build error'
Tue Nov 21 18:56:17 2023 - ERROR - option: --no_build error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_generate_website_2_data.sh line 95'
+ message='oe_test_nototools_base_generate_website_2_data.sh line 95'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_generate_website_2_data.sh line 95'
Tue Nov 21 18:56:18 2023 - ERROR - oe_test_nototools_base_generate_website_2_data.sh line 95
+ '[' 0 -eq 1 ']'
+ return 0
+ for i in "ttf" "TTC" "otf"
+ generate_website_2_data.py --debug ttf
Traceback (most recent call last):
  File "/usr/bin/generate_website_2_data.py", line 38, in <module>
    from nototools import create_image
  File "/usr/lib/python3.10/site-packages/nototools/create_image.py", line 32, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --debug ttf error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --debug ttf error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --debug ttf error'
+ LOG_ERROR 'option: --debug ttf error'
+ message='option: --debug ttf error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --debug ttf error'
Tue Nov 21 18:56:20 2023 - ERROR - option: --debug ttf error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_generate_website_2_data.sh line 101'
+ message='oe_test_nototools_base_generate_website_2_data.sh line 101'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_generate_website_2_data.sh line 101'
Tue Nov 21 18:56:20 2023 - ERROR - oe_test_nototools_base_generate_website_2_data.sh line 101
+ '[' 0 -eq 1 ']'
+ return 0
+ for i in "ttf" "TTC" "otf"
+ generate_website_2_data.py --debug TTC
Traceback (most recent call last):
  File "/usr/bin/generate_website_2_data.py", line 38, in <module>
    from nototools import create_image
  File "/usr/lib/python3.10/site-packages/nototools/create_image.py", line 32, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --debug TTC error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --debug TTC error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --debug TTC error'
+ LOG_ERROR 'option: --debug TTC error'
+ message='option: --debug TTC error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --debug TTC error'
Tue Nov 21 18:56:22 2023 - ERROR - option: --debug TTC error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_generate_website_2_data.sh line 101'
+ message='oe_test_nototools_base_generate_website_2_data.sh line 101'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_generate_website_2_data.sh line 101'
Tue Nov 21 18:56:23 2023 - ERROR - oe_test_nototools_base_generate_website_2_data.sh line 101
+ '[' 0 -eq 1 ']'
+ return 0
+ for i in "ttf" "TTC" "otf"
+ generate_website_2_data.py --debug otf
Traceback (most recent call last):
  File "/usr/bin/generate_website_2_data.py", line 38, in <module>
    from nototools import create_image
  File "/usr/lib/python3.10/site-packages/nototools/create_image.py", line 32, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --debug otf error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --debug otf error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --debug otf error'
+ LOG_ERROR 'option: --debug otf error'
+ message='option: --debug otf error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --debug otf error'
Tue Nov 21 18:56:25 2023 - ERROR - option: --debug otf error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_generate_website_2_data.sh line 101'
+ message='oe_test_nototools_base_generate_website_2_data.sh line 101'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_generate_website_2_data.sh line 101'
Tue Nov 21 18:56:25 2023 - ERROR - oe_test_nototools_base_generate_website_2_data.sh line 101
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Nov 21 18:56:26 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 23
+ test 23 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Nov 21 18:56:26 2023 - ERROR - failed to execute the case.
+ exit 23
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Nov 21 18:56:27 2023 - INFO  - Start to restore the test environment.
+ common_post
+ rm -rf /tmp/nototools.SRC.y0sdIVYGuKDN /root/.notoconfig
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpo86vj2o4 ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpo86vj2o4
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Nov 21 18:57:25 2023 - INFO  - End to restore the test environment.
