+ source /root/GitRepo/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/GitRepo/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Wed Apr  5 10:50:47 2023 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL etcd
+ pkgs=etcd
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/GitRepo/mugen/libs/locallibs/rpm_manage.py install --pkgs etcd --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpq__sce1u
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpq__sce1u
+ systemctl start etcd
Job for etcd.service failed because the control process exited with error code.
See "systemctl status etcd.service" and "journalctl -xeu etcd.service" for details.
++ rpm -qa etcd
++ awk -F - '{print$2}'
+ version=3.4.14
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Wed Apr  5 10:51:45 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Wed Apr  5 10:51:46 2023 - INFO  - Start to run test.
+ systemctl status etcd
+ grep 'active (running)'
+ CHECK_RESULT 1 0 0 'Check etcd.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcd.service start failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcd.service start failed'
+ LOG_ERROR 'Check etcd.service start failed'
+ message='Check etcd.service start failed'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcd.service start failed'
Wed Apr  5 10:51:47 2023 - ERROR - Check etcd.service start failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_01.sh line 30'
+ message='oe_test_etcd_01.sh line 30'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_01.sh line 30'
Wed Apr  5 10:51:48 2023 - ERROR - oe_test_etcd_01.sh line 30
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i Usage:
+ etcd --help
+ CHECK_RESULT 1 0 0 'Check etcd --help failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcd --help failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcd --help failed.'
+ LOG_ERROR 'Check etcd --help failed.'
+ message='Check etcd --help failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcd --help failed.'
Wed Apr  5 10:51:49 2023 - ERROR - Check etcd --help failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_01.sh line 32'
+ message='oe_test_etcd_01.sh line 32'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_01.sh line 32'
Wed Apr  5 10:51:50 2023 - ERROR - oe_test_etcd_01.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
++ etcd --version
++ awk '{print $3}'
++ head -1
+ test unsupported == 3.4.14
+ CHECK_RESULT 1 0 0 'Check etcd --version failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcd --version failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcd --version failed.'
+ LOG_ERROR 'Check etcd --version failed.'
+ message='Check etcd --version failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcd --version failed.'
Wed Apr  5 10:51:51 2023 - ERROR - Check etcd --version failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_01.sh line 34'
+ message='oe_test_etcd_01.sh line 34'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_01.sh line 34'
Wed Apr  5 10:51:52 2023 - ERROR - oe_test_etcd_01.sh line 34
+ '[' 0 -eq 1 ']'
+ return 0
++ etcdctl version
++ awk '{print $3}'
++ head -1
+ test 3.4.14 == 3.4.14
+ CHECK_RESULT 0 0 0 'Check etcdctl version failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl version failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep -i USAGE:
+ etcdctl help
USAGE:
+ CHECK_RESULT 0 0 0 'Check etcdctl help failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl help failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ etcdctl --endpoints=http://127.0.0.1:2379 put a 123
+ grep -i OK
{"level":"warn","ts":"2023-04-05T10:51:58.802+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-175ea91d-40e0-4622-b386-2fbad4dba47e/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
+ CHECK_RESULT 1 0 0 'Check etcdctl --endpoints put command failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl --endpoints put command failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcdctl --endpoints put command failed.'
+ LOG_ERROR 'Check etcdctl --endpoints put command failed.'
+ message='Check etcdctl --endpoints put command failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcdctl --endpoints put command failed.'
Wed Apr  5 10:51:59 2023 - ERROR - Check etcdctl --endpoints put command failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_01.sh line 40'
+ message='oe_test_etcd_01.sh line 40'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_01.sh line 40'
Wed Apr  5 10:52:00 2023 - ERROR - oe_test_etcd_01.sh line 40
+ '[' 0 -eq 1 ']'
+ return 0
+ etcdctl --endpoints=http://127.0.0.1:2379 get a
+ grep 123
{"level":"warn","ts":"2023-04-05T10:52:05.890+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-2611f21a-8aa0-4d6c-8672-cceaa90b0b7f/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
+ CHECK_RESULT 1 0 0 'Check etcdctl --endpoints get command failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl --endpoints get command failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcdctl --endpoints get command failed.'
+ LOG_ERROR 'Check etcdctl --endpoints get command failed.'
+ message='Check etcdctl --endpoints get command failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcdctl --endpoints get command failed.'
Wed Apr  5 10:52:06 2023 - ERROR - Check etcdctl --endpoints get command failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_01.sh line 42'
+ message='oe_test_etcd_01.sh line 42'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_01.sh line 42'
Wed Apr  5 10:52:07 2023 - ERROR - oe_test_etcd_01.sh line 42
+ '[' 0 -eq 1 ']'
+ return 0
+ etcdctl --endpoints=http://127.0.0.1:2379 get a -w=json
+ grep version
{"level":"warn","ts":"2023-04-05T10:52:12.810+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-0fe7fbc8-1436-4466-ba8d-a02cfb16a9c9/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
+ CHECK_RESULT 1 0 0 'Check etcdctl --endpoints get -w=json command failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl --endpoints get -w=json command failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcdctl --endpoints get -w=json command failed.'
+ LOG_ERROR 'Check etcdctl --endpoints get -w=json command failed.'
+ message='Check etcdctl --endpoints get -w=json command failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcdctl --endpoints get -w=json command failed.'
Wed Apr  5 10:52:13 2023 - ERROR - Check etcdctl --endpoints get -w=json command failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_01.sh line 44'
+ message='oe_test_etcd_01.sh line 44'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_01.sh line 44'
Wed Apr  5 10:52:14 2023 - ERROR - oe_test_etcd_01.sh line 44
+ '[' 0 -eq 1 ']'
+ return 0
+ etcdctl --endpoints=http://127.0.0.1:2379 del a
+ grep 1
{"level":"warn","ts":"2023-04-05T10:52:20.007+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-04e7962a-aa3b-4241-af6b-ec4c74d1d5b5/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
+ CHECK_RESULT 1 0 0 'Check etcdctl --endpoints del command failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl --endpoints del command failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcdctl --endpoints del command failed.'
+ LOG_ERROR 'Check etcdctl --endpoints del command failed.'
+ message='Check etcdctl --endpoints del command failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcdctl --endpoints del command failed.'
Wed Apr  5 10:52:20 2023 - ERROR - Check etcdctl --endpoints del command failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_01.sh line 46'
+ message='oe_test_etcd_01.sh line 46'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_01.sh line 46'
Wed Apr  5 10:52:21 2023 - ERROR - oe_test_etcd_01.sh line 46
+ '[' 0 -eq 1 ']'
+ return 0
+ etcdctl --endpoints=http://127.0.0.1:2379 del a
+ grep 0
{"level":"warn","ts":"2023-04-05T10:52:26.938+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-ef41f27a-7166-46da-95a0-6a9c1c7756c7/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
+ CHECK_RESULT 1 0 0 'Check etcdctl --endpoints del command failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl --endpoints del command failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcdctl --endpoints del command failed.'
+ LOG_ERROR 'Check etcdctl --endpoints del command failed.'
+ message='Check etcdctl --endpoints del command failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcdctl --endpoints del command failed.'
Wed Apr  5 10:52:27 2023 - ERROR - Check etcdctl --endpoints del command failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_01.sh line 48'
+ message='oe_test_etcd_01.sh line 48'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_01.sh line 48'
Wed Apr  5 10:52:28 2023 - ERROR - oe_test_etcd_01.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Wed Apr  5 10:52:29 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 8
+ test 8 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Apr  5 10:52:29 2023 - ERROR - failed to execute the case.
+ exit 8
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Wed Apr  5 10:52:30 2023 - INFO  - Start to restore the test environment.
+ systemctl stop etcd
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpq__sce1u ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/GitRepo/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpq__sce1u
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Wed Apr  5 10:52:49 2023 - INFO  - End to restore the test environment.
