+ source ../common/common.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n function ']'
+ config_params
+ LOG_INFO 'Start to config params of the case.'
+ message='Start to config params of the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to config params of the case.'
Tue Nov 21 17:26:28 2023 - INFO  - Start to config params of the case.
++ mktemp -d -t nototools.XXXXXXXXXXXX
+ TMP_DIR=/tmp/nototools.N2R9Ad8MwlM8
+ TEST_FILE_1=font1.ttf
+ TEST_FILE_2=font2.ttf
+ MISS_LIST='glyph00569 glyph00568'
+ LOG_INFO 'End to config params of the case.'
+ message='End to config params of the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to config params of the case.'
Tue Nov 21 17:26:28 2023 - INFO  - End to config params of the case.
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Tue Nov 21 17:26:29 2023 - INFO  - Start to prepare the test environment.
+ common_pre
+ pip install -r ../common/requirements.txt
+ DNF_INSTALL 'nototools harfbuzz-devel cpio pango python3-gobject python3-cairo'
+ pkgs='nototools harfbuzz-devel cpio pango python3-gobject python3-cairo'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'nototools harfbuzz-devel cpio pango python3-gobject python3-cairo' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmp14fs4_e6
+ '[' -z '' ']'
+ tmpfile=/tmp/tmp14fs4_e6
+ notoconfig_pre
++ mktemp -d -t nototools.SRC.XXXXXXXXXXXX
+ TMP_SRCDIR=/tmp/nototools.SRC.Tneikb3ZtAPW
+ yumdownloader --source nototools --destdir /tmp/nototools.SRC.Tneikb3ZtAPW
No package nototools-0.2.17-1.oe2303.src available.
Exiting due to strict setting.
Error: No package nototools-0.2.17-1.oe2303.src available.
+ cpio -div -D /tmp/nototools.SRC.Tneikb3ZtAPW
+ rpm2cpio '/tmp/nototools.SRC.Tneikb3ZtAPW/*.rpm'
rpm2cpio: /tmp/nototools.SRC.Tneikb3ZtAPW/*.rpm: No such file or directory
+ tar -zxf '/tmp/nototools.SRC.Tneikb3ZtAPW/*.tar.gz' --strip-components 1 --directory /tmp/nototools.SRC.Tneikb3ZtAPW
tar (child): /tmp/nototools.SRC.Tneikb3ZtAPW/*.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
+ echo noto_tools=/tmp/nototools.SRC.Tneikb3ZtAPW
+ for src in "fonts" "cjk" "emoji"
+ echo noto_fonts=/tmp/nototools.SRC.Tneikb3ZtAPW/noto-fonts
+ for src in "fonts" "cjk" "emoji"
+ echo noto_cjk=/tmp/nototools.SRC.Tneikb3ZtAPW/noto-cjk
+ for src in "fonts" "cjk" "emoji"
+ echo noto_emoji=/tmp/nototools.SRC.Tneikb3ZtAPW/noto-emoji
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Tue Nov 21 17:33:01 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Nov 21 17:33:01 2023 - INFO  - Start to run test.
+ notodiff -h
+ grep -q usage
Traceback (most recent call last):
  File "/usr/bin/notodiff", line 33, in <module>
    sys.exit(load_entry_point('notofonttools==0.2.17', 'console_scripts', 'notodiff')())
  File "/usr/bin/notodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nototools/notodiff.py", line 33, in <module>
    from nototools import gpos_diff, gsub_diff, shape_diff
  File "/usr/lib/python3.10/site-packages/nototools/shape_diff.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
+ CHECK_RESULT 1 0 0 'option: -h error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: -h error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: -h error'
+ LOG_ERROR 'option: -h error'
+ message='option: -h error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: -h error'
Tue Nov 21 17:33:03 2023 - ERROR - option: -h error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_0-2_notodiff.sh line 50'
+ message='oe_test_nototools_0-2_notodiff.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_0-2_notodiff.sh line 50'
Tue Nov 21 17:33:04 2023 - ERROR - oe_test_nototools_0-2_notodiff.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ notocoverage --help
+ grep -q usage
+ CHECK_RESULT 0 0 0 'option: --help error'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='option: --help error'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ notodiff --before test_input/test_input_1/font1.ttf --after test_input/test_input_1/font2.ttf
+ grep -q '17 differences in glyph shape'
Traceback (most recent call last):
  File "/usr/bin/notodiff", line 33, in <module>
    sys.exit(load_entry_point('notofonttools==0.2.17', 'console_scripts', 'notodiff')())
  File "/usr/bin/notodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nototools/notodiff.py", line 33, in <module>
    from nototools import gpos_diff, gsub_diff, shape_diff
  File "/usr/lib/python3.10/site-packages/nototools/shape_diff.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
+ CHECK_RESULT 1 0 0 'option: --before,--after error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --before,--after error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --before,--after error'
+ LOG_ERROR 'option: --before,--after error'
+ message='option: --before,--after error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --before,--after error'
Tue Nov 21 17:33:07 2023 - ERROR - option: --before,--after error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_0-2_notodiff.sh line 56'
+ message='oe_test_nototools_0-2_notodiff.sh line 56'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_0-2_notodiff.sh line 56'
Tue Nov 21 17:33:08 2023 - ERROR - oe_test_nototools_0-2_notodiff.sh line 56
+ '[' 0 -eq 1 ']'
+ return 0
+ notodiff --before test_input/test_input_1/font1.ttf --after test_input/test_input_1/font2.ttf -t area
+ grep -q '17 differences in glyph shape'
Traceback (most recent call last):
  File "/usr/bin/notodiff", line 33, in <module>
    sys.exit(load_entry_point('notofonttools==0.2.17', 'console_scripts', 'notodiff')())
  File "/usr/bin/notodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nototools/notodiff.py", line 33, in <module>
    from nototools import gpos_diff, gsub_diff, shape_diff
  File "/usr/lib/python3.10/site-packages/nototools/shape_diff.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
+ CHECK_RESULT 1 0 0 'option: -t area error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: -t area error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: -t area error'
+ LOG_ERROR 'option: -t area error'
+ message='option: -t area error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: -t area error'
Tue Nov 21 17:33:10 2023 - ERROR - option: -t area error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_0-2_notodiff.sh line 60'
+ message='oe_test_nototools_0-2_notodiff.sh line 60'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_0-2_notodiff.sh line 60'
Tue Nov 21 17:33:10 2023 - ERROR - oe_test_nototools_0-2_notodiff.sh line 60
+ '[' 0 -eq 1 ']'
+ return 0
+ notodiff --before test_input/test_input_1/font1.ttf --after test_input/test_input_1/font2.ttf --diff-type shape
+ grep -q '17 differences in glyph shape'
Traceback (most recent call last):
  File "/usr/bin/notodiff", line 33, in <module>
    sys.exit(load_entry_point('notofonttools==0.2.17', 'console_scripts', 'notodiff')())
  File "/usr/bin/notodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nototools/notodiff.py", line 33, in <module>
    from nototools import gpos_diff, gsub_diff, shape_diff
  File "/usr/lib/python3.10/site-packages/nototools/shape_diff.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
+ CHECK_RESULT 1 0 0 'option: --diff-type shape error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --diff-type shape error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --diff-type shape error'
+ LOG_ERROR 'option: --diff-type shape error'
+ message='option: --diff-type shape error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --diff-type shape error'
Tue Nov 21 17:33:12 2023 - ERROR - option: --diff-type shape error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_0-2_notodiff.sh line 62'
+ message='oe_test_nototools_0-2_notodiff.sh line 62'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_0-2_notodiff.sh line 62'
Tue Nov 21 17:33:12 2023 - ERROR - oe_test_nototools_0-2_notodiff.sh line 62
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -q '17 differences in glyph shape'
+ notodiff --before test_input/test_input_1/font1.ttf --after test_input/test_input_1/font2.ttf -t area-shape-product
Traceback (most recent call last):
  File "/usr/bin/notodiff", line 33, in <module>
    sys.exit(load_entry_point('notofonttools==0.2.17', 'console_scripts', 'notodiff')())
  File "/usr/bin/notodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nototools/notodiff.py", line 33, in <module>
    from nototools import gpos_diff, gsub_diff, shape_diff
  File "/usr/lib/python3.10/site-packages/nototools/shape_diff.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
+ CHECK_RESULT 1 0 0 'option: -t area-shape-product error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: -t area-shape-product error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: -t area-shape-product error'
+ LOG_ERROR 'option: -t area-shape-product error'
+ message='option: -t area-shape-product error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: -t area-shape-product error'
Tue Nov 21 17:33:14 2023 - ERROR - option: -t area-shape-product error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_0-2_notodiff.sh line 64'
+ message='oe_test_nototools_0-2_notodiff.sh line 64'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_0-2_notodiff.sh line 64'
Tue Nov 21 17:33:15 2023 - ERROR - oe_test_nototools_0-2_notodiff.sh line 64
+ '[' 0 -eq 1 ']'
+ return 0
+ notodiff --before test_input/test_input_1/font1.ttf --after test_input/test_input_1/font2.ttf --diff-type rendered
+ grep -q '3 differences in glyph shape'
Traceback (most recent call last):
  File "/usr/bin/notodiff", line 33, in <module>
    sys.exit(load_entry_point('notofonttools==0.2.17', 'console_scripts', 'notodiff')())
  File "/usr/bin/notodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nototools/notodiff.py", line 33, in <module>
    from nototools import gpos_diff, gsub_diff, shape_diff
  File "/usr/lib/python3.10/site-packages/nototools/shape_diff.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
+ CHECK_RESULT 1 0 0 'option: --diff-type rendered error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --diff-type rendered error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --diff-type rendered error'
+ LOG_ERROR 'option: --diff-type rendered error'
+ message='option: --diff-type rendered error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --diff-type rendered error'
Tue Nov 21 17:33:18 2023 - ERROR - option: --diff-type rendered error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_0-2_notodiff.sh line 66'
+ message='oe_test_nototools_0-2_notodiff.sh line 66'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_0-2_notodiff.sh line 66'
Tue Nov 21 17:33:18 2023 - ERROR - oe_test_nototools_0-2_notodiff.sh line 66
+ '[' 0 -eq 1 ']'
+ return 0
+ notodiff --before test_input/test_input_1/font1.ttf --after test_input/test_input_1/font2.ttf -t gsub
+ grep -q '9 differences in GSUB rules'
Traceback (most recent call last):
  File "/usr/bin/notodiff", line 33, in <module>
    sys.exit(load_entry_point('notofonttools==0.2.17', 'console_scripts', 'notodiff')())
  File "/usr/bin/notodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nototools/notodiff.py", line 33, in <module>
    from nototools import gpos_diff, gsub_diff, shape_diff
  File "/usr/lib/python3.10/site-packages/nototools/shape_diff.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
+ CHECK_RESULT 1 0 0 'option: -t gsub error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: -t gsub error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: -t gsub error'
+ LOG_ERROR 'option: -t gsub error'
+ message='option: -t gsub error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: -t gsub error'
Tue Nov 21 17:33:20 2023 - ERROR - option: -t gsub error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_0-2_notodiff.sh line 68'
+ message='oe_test_nototools_0-2_notodiff.sh line 68'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_0-2_notodiff.sh line 68'
Tue Nov 21 17:33:21 2023 - ERROR - oe_test_nototools_0-2_notodiff.sh line 68
+ '[' 0 -eq 1 ']'
+ return 0
+ notodiff --before test_input/test_input_1/font1.ttf --after test_input/test_input_1/font2.ttf --diff-type gpos
+ grep -qE '115 differences in mark-to-mark positioning rule coverage|0 differences in mark-to-mark positioning rule values'
Traceback (most recent call last):
  File "/usr/bin/notodiff", line 33, in <module>
    sys.exit(load_entry_point('notofonttools==0.2.17', 'console_scripts', 'notodiff')())
  File "/usr/bin/notodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nototools/notodiff.py", line 33, in <module>
    from nototools import gpos_diff, gsub_diff, shape_diff
  File "/usr/lib/python3.10/site-packages/nototools/shape_diff.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
+ CHECK_RESULT 1 0 0 'option: --diff-type gpos error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --diff-type gpos error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --diff-type gpos error'
+ LOG_ERROR 'option: --diff-type gpos error'
+ message='option: --diff-type gpos error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --diff-type gpos error'
Tue Nov 21 17:33:22 2023 - ERROR - option: --diff-type gpos error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_0-2_notodiff.sh line 70'
+ message='oe_test_nototools_0-2_notodiff.sh line 70'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_0-2_notodiff.sh line 70'
Tue Nov 21 17:33:23 2023 - ERROR - oe_test_nototools_0-2_notodiff.sh line 70
+ '[' 0 -eq 1 ']'
+ return 0
+ notodiff --before test_input/test_input_1 --after test_input/test_input_2 -m '*.ttf'
+ grep -q '17 differences in glyph shape'
Traceback (most recent call last):
  File "/usr/bin/notodiff", line 33, in <module>
    sys.exit(load_entry_point('notofonttools==0.2.17', 'console_scripts', 'notodiff')())
  File "/usr/bin/notodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nototools/notodiff.py", line 33, in <module>
    from nototools import gpos_diff, gsub_diff, shape_diff
  File "/usr/lib/python3.10/site-packages/nototools/shape_diff.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
+ CHECK_RESULT 1 0 0 'option: -m error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: -m error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: -m error'
+ LOG_ERROR 'option: -m error'
+ message='option: -m error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: -m error'
Tue Nov 21 17:33:25 2023 - ERROR - option: -m error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_0-2_notodiff.sh line 74'
+ message='oe_test_nototools_0-2_notodiff.sh line 74'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_0-2_notodiff.sh line 74'
Tue Nov 21 17:33:25 2023 - ERROR - oe_test_nototools_0-2_notodiff.sh line 74
+ '[' 0 -eq 1 ']'
+ return 0
+ notodiff --before test_input/test_input_1 --after test_input/test_input_2 --match '*.ttf'
+ grep -q '17 differences in glyph shape'
Traceback (most recent call last):
  File "/usr/bin/notodiff", line 33, in <module>
    sys.exit(load_entry_point('notofonttools==0.2.17', 'console_scripts', 'notodiff')())
  File "/usr/bin/notodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nototools/notodiff.py", line 33, in <module>
    from nototools import gpos_diff, gsub_diff, shape_diff
  File "/usr/lib/python3.10/site-packages/nototools/shape_diff.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
+ CHECK_RESULT 1 0 0 'option: --match error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --match error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --match error'
+ LOG_ERROR 'option: --match error'
+ message='option: --match error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --match error'
Tue Nov 21 17:33:27 2023 - ERROR - option: --match error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_0-2_notodiff.sh line 76'
+ message='oe_test_nototools_0-2_notodiff.sh line 76'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_0-2_notodiff.sh line 76'
Tue Nov 21 17:33:28 2023 - ERROR - oe_test_nototools_0-2_notodiff.sh line 76
+ '[' 0 -eq 1 ']'
+ return 0
+ notodiff --before test_input/test_input_1/font1.ttf --after test_input/test_input_1/font2.ttf -l 10
+ grep -q '17 differences in glyph shape'
Traceback (most recent call last):
  File "/usr/bin/notodiff", line 33, in <module>
    sys.exit(load_entry_point('notofonttools==0.2.17', 'console_scripts', 'notodiff')())
  File "/usr/bin/notodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nototools/notodiff.py", line 33, in <module>
    from nototools import gpos_diff, gsub_diff, shape_diff
  File "/usr/lib/python3.10/site-packages/nototools/shape_diff.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
+ CHECK_RESULT 1 0 0 'option: -l error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: -l error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: -l error'
+ LOG_ERROR 'option: -l error'
+ message='option: -l error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: -l error'
Tue Nov 21 17:33:29 2023 - ERROR - option: -l error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_0-2_notodiff.sh line 80'
+ message='oe_test_nototools_0-2_notodiff.sh line 80'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_0-2_notodiff.sh line 80'
Tue Nov 21 17:33:30 2023 - ERROR - oe_test_nototools_0-2_notodiff.sh line 80
+ '[' 0 -eq 1 ']'
+ return 0
+ notodiff --before test_input/test_input_1/font1.ttf --after test_input/test_input_1/font2.ttf --out-lines 10
+ grep -q '17 differences in glyph shape'
Traceback (most recent call last):
  File "/usr/bin/notodiff", line 33, in <module>
    sys.exit(load_entry_point('notofonttools==0.2.17', 'console_scripts', 'notodiff')())
  File "/usr/bin/notodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nototools/notodiff.py", line 33, in <module>
    from nototools import gpos_diff, gsub_diff, shape_diff
  File "/usr/lib/python3.10/site-packages/nototools/shape_diff.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
+ CHECK_RESULT 1 0 0 'option: --out-lines error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --out-lines error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --out-lines error'
+ LOG_ERROR 'option: --out-lines error'
+ message='option: --out-lines error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --out-lines error'
Tue Nov 21 17:33:32 2023 - ERROR - option: --out-lines error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_0-2_notodiff.sh line 82'
+ message='oe_test_nototools_0-2_notodiff.sh line 82'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_0-2_notodiff.sh line 82'
Tue Nov 21 17:33:32 2023 - ERROR - oe_test_nototools_0-2_notodiff.sh line 82
+ '[' 0 -eq 1 ']'
+ return 0
+ notodiff --before test_input/test_input_1/font1.ttf --after test_input/test_input_1/font2.ttf -w glyph00569 glyph00568
+ grep -q '15 differences in glyph shape'
Traceback (most recent call last):
  File "/usr/bin/notodiff", line 33, in <module>
    sys.exit(load_entry_point('notofonttools==0.2.17', 'console_scripts', 'notodiff')())
  File "/usr/bin/notodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nototools/notodiff.py", line 33, in <module>
    from nototools import gpos_diff, gsub_diff, shape_diff
  File "/usr/lib/python3.10/site-packages/nototools/shape_diff.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
+ CHECK_RESULT 1 0 0 'option: -w error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: -w error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: -w error'
+ LOG_ERROR 'option: -w error'
+ message='option: -w error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: -w error'
Tue Nov 21 17:33:34 2023 - ERROR - option: -w error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_0-2_notodiff.sh line 86'
+ message='oe_test_nototools_0-2_notodiff.sh line 86'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_0-2_notodiff.sh line 86'
Tue Nov 21 17:33:35 2023 - ERROR - oe_test_nototools_0-2_notodiff.sh line 86
+ '[' 0 -eq 1 ']'
+ return 0
+ notodiff --before test_input/test_input_1/font1.ttf --after test_input/test_input_1/font2.ttf --whitelist glyph00569 glyph00568
+ grep -q '15 differences in glyph shape'
Traceback (most recent call last):
  File "/usr/bin/notodiff", line 33, in <module>
    sys.exit(load_entry_point('notofonttools==0.2.17', 'console_scripts', 'notodiff')())
  File "/usr/bin/notodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nototools/notodiff.py", line 33, in <module>
    from nototools import gpos_diff, gsub_diff, shape_diff
  File "/usr/lib/python3.10/site-packages/nototools/shape_diff.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
+ CHECK_RESULT 1 0 0 'option: -w error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: -w error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: -w error'
+ LOG_ERROR 'option: -w error'
+ message='option: -w error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: -w error'
Tue Nov 21 17:33:37 2023 - ERROR - option: -w error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_0-2_notodiff.sh line 88'
+ message='oe_test_nototools_0-2_notodiff.sh line 88'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_0-2_notodiff.sh line 88'
Tue Nov 21 17:33:37 2023 - ERROR - oe_test_nototools_0-2_notodiff.sh line 88
+ '[' 0 -eq 1 ']'
+ return 0
+ for i in "64" "128"
+ notodiff --before test_input/test_input_1/font1.ttf --after test_input/test_input_1/font2.ttf -t rendered --font-size 64
+ grep -q '3 differences in glyph shape'
Traceback (most recent call last):
  File "/usr/bin/notodiff", line 33, in <module>
    sys.exit(load_entry_point('notofonttools==0.2.17', 'console_scripts', 'notodiff')())
  File "/usr/bin/notodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nototools/notodiff.py", line 33, in <module>
    from nototools import gpos_diff, gsub_diff, shape_diff
  File "/usr/lib/python3.10/site-packages/nototools/shape_diff.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
+ CHECK_RESULT 1 0 0 'option: --font-size 64 error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --font-size 64 error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --font-size 64 error'
+ LOG_ERROR 'option: --font-size 64 error'
+ message='option: --font-size 64 error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --font-size 64 error'
Tue Nov 21 17:33:39 2023 - ERROR - option: --font-size 64 error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_0-2_notodiff.sh line 94'
+ message='oe_test_nototools_0-2_notodiff.sh line 94'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_0-2_notodiff.sh line 94'
Tue Nov 21 17:33:39 2023 - ERROR - oe_test_nototools_0-2_notodiff.sh line 94
+ '[' 0 -eq 1 ']'
+ return 0
+ for i in "64" "128"
+ notodiff --before test_input/test_input_1/font1.ttf --after test_input/test_input_1/font2.ttf -t rendered --font-size 128
+ grep -q '3 differences in glyph shape'
Traceback (most recent call last):
  File "/usr/bin/notodiff", line 33, in <module>
    sys.exit(load_entry_point('notofonttools==0.2.17', 'console_scripts', 'notodiff')())
  File "/usr/bin/notodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nototools/notodiff.py", line 33, in <module>
    from nototools import gpos_diff, gsub_diff, shape_diff
  File "/usr/lib/python3.10/site-packages/nototools/shape_diff.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
+ CHECK_RESULT 1 0 0 'option: --font-size 128 error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --font-size 128 error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --font-size 128 error'
+ LOG_ERROR 'option: --font-size 128 error'
+ message='option: --font-size 128 error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --font-size 128 error'
Tue Nov 21 17:33:41 2023 - ERROR - option: --font-size 128 error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_0-2_notodiff.sh line 94'
+ message='oe_test_nototools_0-2_notodiff.sh line 94'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_0-2_notodiff.sh line 94'
Tue Nov 21 17:33:42 2023 - ERROR - oe_test_nototools_0-2_notodiff.sh line 94
+ '[' 0 -eq 1 ']'
+ return 0
+ notodiff --before test_input/test_input_1/font1.ttf --after test_input/test_input_1/font2.ttf -t rendered --render-path /tmp/nototools.N2R9Ad8MwlM8
+ grep -q '3 differences in glyph shape'
Traceback (most recent call last):
  File "/usr/bin/notodiff", line 33, in <module>
    sys.exit(load_entry_point('notofonttools==0.2.17', 'console_scripts', 'notodiff')())
  File "/usr/bin/notodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nototools/notodiff.py", line 33, in <module>
    from nototools import gpos_diff, gsub_diff, shape_diff
  File "/usr/lib/python3.10/site-packages/nototools/shape_diff.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
+ CHECK_RESULT 1 0 0 'option: --render-path error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --render-path error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --render-path error'
+ LOG_ERROR 'option: --render-path error'
+ message='option: --render-path error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --render-path error'
Tue Nov 21 17:33:44 2023 - ERROR - option: --render-path error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_0-2_notodiff.sh line 99'
+ message='oe_test_nototools_0-2_notodiff.sh line 99'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_0-2_notodiff.sh line 99'
Tue Nov 21 17:33:45 2023 - ERROR - oe_test_nototools_0-2_notodiff.sh line 99
+ '[' 0 -eq 1 ']'
+ return 0
+ notodiff --before test_input/test_input_1/font1.ttf --after test_input/test_input_1/font2.ttf --diff-threshold 1
+ grep -q '17 differences in glyph shape'
Traceback (most recent call last):
  File "/usr/bin/notodiff", line 33, in <module>
    sys.exit(load_entry_point('notofonttools==0.2.17', 'console_scripts', 'notodiff')())
  File "/usr/bin/notodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nototools/notodiff.py", line 33, in <module>
    from nototools import gpos_diff, gsub_diff, shape_diff
  File "/usr/lib/python3.10/site-packages/nototools/shape_diff.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
+ CHECK_RESULT 1 0 0 'option: --diff-threshold error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --diff-threshold error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --diff-threshold error'
+ LOG_ERROR 'option: --diff-threshold error'
+ message='option: --diff-threshold error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --diff-threshold error'
Tue Nov 21 17:33:47 2023 - ERROR - option: --diff-threshold error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_0-2_notodiff.sh line 103'
+ message='oe_test_nototools_0-2_notodiff.sh line 103'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_0-2_notodiff.sh line 103'
Tue Nov 21 17:33:48 2023 - ERROR - oe_test_nototools_0-2_notodiff.sh line 103
+ '[' 0 -eq 1 ']'
+ return 0
+ for i in "debug" "info" "warning" "critical" "error"
+ notodiff --before test_input/test_input_1/font1.ttf --after test_input/test_input_1/font2.ttf --verbose debug
+ grep -q '17 differences in glyph shape'
Traceback (most recent call last):
  File "/usr/bin/notodiff", line 33, in <module>
    sys.exit(load_entry_point('notofonttools==0.2.17', 'console_scripts', 'notodiff')())
  File "/usr/bin/notodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nototools/notodiff.py", line 33, in <module>
    from nototools import gpos_diff, gsub_diff, shape_diff
  File "/usr/lib/python3.10/site-packages/nototools/shape_diff.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
+ CHECK_RESULT 1 0 0 'option: --verbose debug error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --verbose debug error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --verbose debug error'
+ LOG_ERROR 'option: --verbose debug error'
+ message='option: --verbose debug error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --verbose debug error'
Tue Nov 21 17:33:50 2023 - ERROR - option: --verbose debug error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_0-2_notodiff.sh line 109'
+ message='oe_test_nototools_0-2_notodiff.sh line 109'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_0-2_notodiff.sh line 109'
Tue Nov 21 17:33:50 2023 - ERROR - oe_test_nototools_0-2_notodiff.sh line 109
+ '[' 0 -eq 1 ']'
+ return 0
+ for i in "debug" "info" "warning" "critical" "error"
+ notodiff --before test_input/test_input_1/font1.ttf --after test_input/test_input_1/font2.ttf --verbose info
+ grep -q '17 differences in glyph shape'
Traceback (most recent call last):
  File "/usr/bin/notodiff", line 33, in <module>
    sys.exit(load_entry_point('notofonttools==0.2.17', 'console_scripts', 'notodiff')())
  File "/usr/bin/notodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nototools/notodiff.py", line 33, in <module>
    from nototools import gpos_diff, gsub_diff, shape_diff
  File "/usr/lib/python3.10/site-packages/nototools/shape_diff.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
+ CHECK_RESULT 1 0 0 'option: --verbose info error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --verbose info error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --verbose info error'
+ LOG_ERROR 'option: --verbose info error'
+ message='option: --verbose info error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --verbose info error'
Tue Nov 21 17:33:52 2023 - ERROR - option: --verbose info error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_0-2_notodiff.sh line 109'
+ message='oe_test_nototools_0-2_notodiff.sh line 109'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_0-2_notodiff.sh line 109'
Tue Nov 21 17:33:53 2023 - ERROR - oe_test_nototools_0-2_notodiff.sh line 109
+ '[' 0 -eq 1 ']'
+ return 0
+ for i in "debug" "info" "warning" "critical" "error"
+ notodiff --before test_input/test_input_1/font1.ttf --after test_input/test_input_1/font2.ttf --verbose warning
+ grep -q '17 differences in glyph shape'
Traceback (most recent call last):
  File "/usr/bin/notodiff", line 33, in <module>
    sys.exit(load_entry_point('notofonttools==0.2.17', 'console_scripts', 'notodiff')())
  File "/usr/bin/notodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nototools/notodiff.py", line 33, in <module>
    from nototools import gpos_diff, gsub_diff, shape_diff
  File "/usr/lib/python3.10/site-packages/nototools/shape_diff.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
+ CHECK_RESULT 1 0 0 'option: --verbose warning error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --verbose warning error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --verbose warning error'
+ LOG_ERROR 'option: --verbose warning error'
+ message='option: --verbose warning error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --verbose warning error'
Tue Nov 21 17:33:55 2023 - ERROR - option: --verbose warning error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_0-2_notodiff.sh line 109'
+ message='oe_test_nototools_0-2_notodiff.sh line 109'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_0-2_notodiff.sh line 109'
Tue Nov 21 17:33:56 2023 - ERROR - oe_test_nototools_0-2_notodiff.sh line 109
+ '[' 0 -eq 1 ']'
+ return 0
+ for i in "debug" "info" "warning" "critical" "error"
+ notodiff --before test_input/test_input_1/font1.ttf --after test_input/test_input_1/font2.ttf --verbose critical
+ grep -q '17 differences in glyph shape'
Traceback (most recent call last):
  File "/usr/bin/notodiff", line 33, in <module>
    sys.exit(load_entry_point('notofonttools==0.2.17', 'console_scripts', 'notodiff')())
  File "/usr/bin/notodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nototools/notodiff.py", line 33, in <module>
    from nototools import gpos_diff, gsub_diff, shape_diff
  File "/usr/lib/python3.10/site-packages/nototools/shape_diff.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
+ CHECK_RESULT 1 0 0 'option: --verbose critical error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --verbose critical error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --verbose critical error'
+ LOG_ERROR 'option: --verbose critical error'
+ message='option: --verbose critical error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --verbose critical error'
Tue Nov 21 17:33:57 2023 - ERROR - option: --verbose critical error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_0-2_notodiff.sh line 109'
+ message='oe_test_nototools_0-2_notodiff.sh line 109'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_0-2_notodiff.sh line 109'
Tue Nov 21 17:33:58 2023 - ERROR - oe_test_nototools_0-2_notodiff.sh line 109
+ '[' 0 -eq 1 ']'
+ return 0
+ for i in "debug" "info" "warning" "critical" "error"
+ notodiff --before test_input/test_input_1/font1.ttf --after test_input/test_input_1/font2.ttf --verbose error
+ grep -q '17 differences in glyph shape'
Traceback (most recent call last):
  File "/usr/bin/notodiff", line 33, in <module>
    sys.exit(load_entry_point('notofonttools==0.2.17', 'console_scripts', 'notodiff')())
  File "/usr/bin/notodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nototools/notodiff.py", line 33, in <module>
    from nototools import gpos_diff, gsub_diff, shape_diff
  File "/usr/lib/python3.10/site-packages/nototools/shape_diff.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
+ CHECK_RESULT 1 0 0 'option: --verbose error error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --verbose error error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --verbose error error'
+ LOG_ERROR 'option: --verbose error error'
+ message='option: --verbose error error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --verbose error error'
Tue Nov 21 17:34:00 2023 - ERROR - option: --verbose error error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_0-2_notodiff.sh line 109'
+ message='oe_test_nototools_0-2_notodiff.sh line 109'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_0-2_notodiff.sh line 109'
Tue Nov 21 17:34:00 2023 - ERROR - oe_test_nototools_0-2_notodiff.sh line 109
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Nov 21 17:34:01 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 23
+ test 23 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Nov 21 17:34:01 2023 - ERROR - failed to execute the case.
+ exit 23
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Nov 21 17:34:02 2023 - INFO  - Start to restore the test environment.
+ rm -rf /tmp/nototools.N2R9Ad8MwlM8
+ common_post
+ rm -rf /tmp/nototools.SRC.Tneikb3ZtAPW /root/.notoconfig
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmp14fs4_e6 ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmp14fs4_e6
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Nov 21 17:35:01 2023 - INFO  - End to restore the test environment.
