+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment'
+ message='Start to prepare the test environment'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment'
Tue Nov 21 22:44:12 2023 - INFO  - Start to prepare the test environment
+ DNF_INSTALL pylint
+ pkgs=pylint
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs pylint --node 1 --tempfile ''
+ tmpfile2=/tmp/tmps9uqzr3v
+ '[' -z '' ']'
+ tmpfile=/tmp/tmps9uqzr3v
+ cat
+ LOG_INFO 'End to prepare the test environment'
+ message='End to prepare the test environment'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment'
Tue Nov 21 22:44:52 2023 - INFO  - End to prepare the test environment
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Nov 21 22:44:53 2023 - INFO  - Start to run test.
+ pylint '--init-hook=import sys; import os; sys.path.append(os.getcwd())' --load-plugins plugin ./common/test.py
+ grep 'Hello world'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L47: pylint --load-plugins <modules> No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L47: pylint --load-plugins <modules> No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L47: pylint --load-plugins <modules> No Pass'
+ LOG_ERROR 'L47: pylint --load-plugins <modules> No Pass'
+ message='L47: pylint --load-plugins <modules> No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L47: pylint --load-plugins <modules> No Pass'
Tue Nov 21 22:45:00 2023 - ERROR - L47: pylint --load-plugins <modules> No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_02.sh line 47'
+ message='oe_test_pylint_02.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_02.sh line 47'
Tue Nov 21 22:45:00 2023 - ERROR - oe_test_pylint_02.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint --fail-under 9 --generate-rcfile
+ grep fail-under=9.0
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L49: pylint --fail-under <score> No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L49: pylint --fail-under <score> No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L49: pylint --fail-under <score> No Pass'
+ LOG_ERROR 'L49: pylint --fail-under <score> No Pass'
+ message='L49: pylint --fail-under <score> No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L49: pylint --fail-under <score> No Pass'
Tue Nov 21 22:45:06 2023 - ERROR - L49: pylint --fail-under <score> No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_02.sh line 49'
+ message='oe_test_pylint_02.sh line 49'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_02.sh line 49'
Tue Nov 21 22:45:07 2023 - ERROR - oe_test_pylint_02.sh line 49
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint -j 1 ./common/test.py
+ grep 'Module test'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L51: pylint -j <n-processes> No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L51: pylint -j <n-processes> No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L51: pylint -j <n-processes> No Pass'
+ LOG_ERROR 'L51: pylint -j <n-processes> No Pass'
+ message='L51: pylint -j <n-processes> No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L51: pylint -j <n-processes> No Pass'
Tue Nov 21 22:45:13 2023 - ERROR - L51: pylint -j <n-processes> No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_02.sh line 51'
+ message='oe_test_pylint_02.sh line 51'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_02.sh line 51'
Tue Nov 21 22:45:14 2023 - ERROR - oe_test_pylint_02.sh line 51
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint --limit-inference-results 10 ./common/test.py
+ grep 'Module test'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L53: pylint --limit-inference-results <number-of-results> No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L53: pylint --limit-inference-results <number-of-results> No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L53: pylint --limit-inference-results <number-of-results> No Pass'
+ LOG_ERROR 'L53: pylint --limit-inference-results <number-of-results> No Pass'
+ message='L53: pylint --limit-inference-results <number-of-results> No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L53: pylint --limit-inference-results <number-of-results> No Pass'
Tue Nov 21 22:45:20 2023 - ERROR - L53: pylint --limit-inference-results <number-of-results> No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_02.sh line 53'
+ message='oe_test_pylint_02.sh line 53'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_02.sh line 53'
Tue Nov 21 22:45:21 2023 - ERROR - oe_test_pylint_02.sh line 53
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint --extension-pkg-whitelist=PyQt5 ./common/test.py
+ grep 'Module test'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L55: pylint --extension-pkg-whitelist pkg No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L55: pylint --extension-pkg-whitelist pkg No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L55: pylint --extension-pkg-whitelist pkg No Pass'
+ LOG_ERROR 'L55: pylint --extension-pkg-whitelist pkg No Pass'
+ message='L55: pylint --extension-pkg-whitelist pkg No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L55: pylint --extension-pkg-whitelist pkg No Pass'
Tue Nov 21 22:45:27 2023 - ERROR - L55: pylint --extension-pkg-whitelist pkg No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_02.sh line 55'
+ message='oe_test_pylint_02.sh line 55'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_02.sh line 55'
Tue Nov 21 22:45:27 2023 - ERROR - oe_test_pylint_02.sh line 55
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint --suggestion-mode n --generate-rcfile
+ grep suggestion-mode=no
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L57: pylint --suggestion-mode <yn> No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L57: pylint --suggestion-mode <yn> No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L57: pylint --suggestion-mode <yn> No Pass'
+ LOG_ERROR 'L57: pylint --suggestion-mode <yn> No Pass'
+ message='L57: pylint --suggestion-mode <yn> No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L57: pylint --suggestion-mode <yn> No Pass'
Tue Nov 21 22:45:34 2023 - ERROR - L57: pylint --suggestion-mode <yn> No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_02.sh line 57'
+ message='oe_test_pylint_02.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_02.sh line 57'
Tue Nov 21 22:45:35 2023 - ERROR - oe_test_pylint_02.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint --exit-zero ./common/test.py
+ grep 'Module test'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L59: pylint --exit-zero No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L59: pylint --exit-zero No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L59: pylint --exit-zero No Pass'
+ LOG_ERROR 'L59: pylint --exit-zero No Pass'
+ message='L59: pylint --exit-zero No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L59: pylint --exit-zero No Pass'
Tue Nov 21 22:45:41 2023 - ERROR - L59: pylint --exit-zero No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_02.sh line 59'
+ message='oe_test_pylint_02.sh line 59'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_02.sh line 59'
Tue Nov 21 22:45:42 2023 - ERROR - oe_test_pylint_02.sh line 59
+ '[' 0 -eq 1 ']'
+ return 0
+ echo s=666
+ pylint --from-stdin test
+ grep 'Module test'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L61: pylint --from-stdin No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L61: pylint --from-stdin No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L61: pylint --from-stdin No Pass'
+ LOG_ERROR 'L61: pylint --from-stdin No Pass'
+ message='L61: pylint --from-stdin No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L61: pylint --from-stdin No Pass'
Tue Nov 21 22:45:48 2023 - ERROR - L61: pylint --from-stdin No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_02.sh line 61'
+ message='oe_test_pylint_02.sh line 61'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_02.sh line 61'
Tue Nov 21 22:45:49 2023 - ERROR - oe_test_pylint_02.sh line 61
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint --generate-rcfile
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ pylint --rcfile=pylint.conf ./common/test.py
+ grep 'Module test'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L64: pylint --rcfile <file> No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L64: pylint --rcfile <file> No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L64: pylint --rcfile <file> No Pass'
+ LOG_ERROR 'L64: pylint --rcfile <file> No Pass'
+ message='L64: pylint --rcfile <file> No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L64: pylint --rcfile <file> No Pass'
Tue Nov 21 22:46:01 2023 - ERROR - L64: pylint --rcfile <file> No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_02.sh line 64'
+ message='oe_test_pylint_02.sh line 64'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_02.sh line 64'
Tue Nov 21 22:46:02 2023 - ERROR - oe_test_pylint_02.sh line 64
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint --help-msg=missing-module-docstring
+ grep missing-module-docstring
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L66: pylint --help-msg <msg-id> No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L66: pylint --help-msg <msg-id> No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L66: pylint --help-msg <msg-id> No Pass'
+ LOG_ERROR 'L66: pylint --help-msg <msg-id> No Pass'
+ message='L66: pylint --help-msg <msg-id> No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L66: pylint --help-msg <msg-id> No Pass'
Tue Nov 21 22:46:08 2023 - ERROR - L66: pylint --help-msg <msg-id> No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_02.sh line 66'
+ message='oe_test_pylint_02.sh line 66'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_02.sh line 66'
Tue Nov 21 22:46:08 2023 - ERROR - oe_test_pylint_02.sh line 66
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Nov 21 22:46:09 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 10
+ test 10 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Nov 21 22:46:10 2023 - ERROR - failed to execute the case.
+ exit 10
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Nov 21 22:46:10 2023 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmps9uqzr3v ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmps9uqzr3v
+ '[' 0 -ne 0 ']'
+ rm -f pylint.conf plugin.py
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Nov 21 22:46:22 2023 - INFO  - End to restore the test environment.
