+ source ../common/common_lib.sh
++ source /root/GitRepo/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/GitRepo/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Wed Apr  5 19:26:24 2023 - INFO  - Start environmental preparation.
++ ip route
++ awk '{print $3}'
++ grep 127.0.0.1
+ eth_name=
++ ethtool -T
++ awk '{print $4}'
++ grep 'PTP Hardware Clock'
oe_test_service_phc2sys.sh: line 25: ethtool: command not found
+ '[' '' == none ']'
+ DNF_INSTALL linuxptp
+ pkgs=linuxptp
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/GitRepo/mugen/libs/locallibs/rpm_manage.py install --pkgs linuxptp --node 1 --tempfile ''
+ tmpfile2=/tmp/tmp06sxxoc3
+ '[' -z '' ']'
+ tmpfile=/tmp/tmp06sxxoc3
+ sed -i 's\-f /etc/ptp4l.conf -i eth0\-f /etc/ptp4l.conf -i \g' /etc/sysconfig/ptp4l
+ systemctl start ptp4l.service
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Wed Apr  5 19:27:04 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Wed Apr  5 19:27:05 2023 - INFO  - Start testing...
+ test_execution phc2sys.service
+ service=phc2sys.service
++ date '+%Y-%m-%d %T'
+ log_time='2023-04-05 19:27:05'
+ test_restart phc2sys.service
+ service=phc2sys.service
+ systemctl restart phc2sys.service
+ CHECK_RESULT 0 0 0 'phc2sys.service restart failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='phc2sys.service restart failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/GitRepo/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status phc2sys.service
+ grep 'Active: active'
     Active: active (running) since Wed 2023-04-05 19:27:05 CST; 6s ago
+ CHECK_RESULT 0 0 0 'phc2sys.service restart failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='phc2sys.service restart failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl stop phc2sys.service
+ CHECK_RESULT 0 0 0 'phc2sys.service stop failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='phc2sys.service stop failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/GitRepo/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ grep 'Active: inactive'
+ systemctl status phc2sys.service
+ CHECK_RESULT 1 0 0 'phc2sys.service stop failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='phc2sys.service stop failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'phc2sys.service stop failed'
+ LOG_ERROR 'phc2sys.service stop failed'
+ message='phc2sys.service stop failed'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'phc2sys.service stop failed'
Wed Apr  5 19:27:19 2023 - ERROR - phc2sys.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 42'
+ message='../common/common_lib.sh line 42'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 42'
Wed Apr  5 19:27:20 2023 - ERROR - ../common/common_lib.sh line 42
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl start phc2sys.service
+ CHECK_RESULT 0 0 0 'phc2sys.service start failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='phc2sys.service start failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/GitRepo/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status phc2sys.service
+ grep 'Active: active'
     Active: active (running) since Wed 2023-04-05 19:27:20 CST; 6s ago
+ CHECK_RESULT 0 0 0 'phc2sys.service start failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='phc2sys.service start failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ test_enabled phc2sys.service
+ service=phc2sys.service
++ systemctl is-enabled phc2sys.service
+ state=disabled
+ '[' disabled == enabled ']'
+ '[' disabled == disabled ']'
++ systemctl enable phc2sys.service
++ grep 'Created symlink'
++ awk '{print $3}'
+ symlink_file=/etc/systemd/system/multi-user.target.wants/phc2sys.service
+ find /etc/systemd/system/multi-user.target.wants/phc2sys.service
/etc/systemd/system/multi-user.target.wants/phc2sys.service
+ CHECK_RESULT 0 0 0 'phc2sys.service enable failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='phc2sys.service enable failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl disable phc2sys.service
Removed /etc/systemd/system/multi-user.target.wants/phc2sys.service.
+ find /etc/systemd/system/multi-user.target.wants/phc2sys.service
find: ‘/etc/systemd/system/multi-user.target.wants/phc2sys.service’: No such file or directory
+ CHECK_RESULT 1 0 1 'phc2sys.service disable failed'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='phc2sys.service disable failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ journalctl --since '2023-04-05 19:27:05' -u phc2sys.service
+ grep -v -i 'DEBUG\|INFO\|WARNING'
+ grep -i 'fail\|error'
Apr 05 19:27:05 openeuler-riscv64 phc2sys[965]: [81.546] uds: sendto failed: No such file or directory
Apr 05 19:27:06 openeuler-riscv64 phc2sys[965]: [82.561] uds: sendto failed: No such file or directory
Apr 05 19:27:07 openeuler-riscv64 phc2sys[965]: [83.565] uds: sendto failed: No such file or directory
Apr 05 19:27:08 openeuler-riscv64 phc2sys[965]: [84.568] uds: sendto failed: No such file or directory
Apr 05 19:27:09 openeuler-riscv64 phc2sys[965]: [85.573] uds: sendto failed: No such file or directory
Apr 05 19:27:10 openeuler-riscv64 phc2sys[965]: [86.576] uds: sendto failed: No such file or directory
Apr 05 19:27:11 openeuler-riscv64 phc2sys[965]: [87.581] uds: sendto failed: No such file or directory
Apr 05 19:27:12 openeuler-riscv64 phc2sys[965]: [87.958] poll failed
Apr 05 19:27:12 openeuler-riscv64 systemd[1]: phc2sys.service: Failed with result 'exit-code'.
Apr 05 19:27:20 openeuler-riscv64 phc2sys[1073]: [96.015] uds: sendto failed: No such file or directory
Apr 05 19:27:21 openeuler-riscv64 phc2sys[1073]: [97.037] uds: sendto failed: No such file or directory
Apr 05 19:27:22 openeuler-riscv64 phc2sys[1073]: [98.040] uds: sendto failed: No such file or directory
Apr 05 19:27:23 openeuler-riscv64 phc2sys[1073]: [99.044] uds: sendto failed: No such file or directory
Apr 05 19:27:24 openeuler-riscv64 phc2sys[1073]: [100.048] uds: sendto failed: No such file or directory
Apr 05 19:27:25 openeuler-riscv64 phc2sys[1073]: [101.052] uds: sendto failed: No such file or directory
Apr 05 19:27:26 openeuler-riscv64 phc2sys[1073]: [102.057] uds: sendto failed: No such file or directory
Apr 05 19:27:27 openeuler-riscv64 phc2sys[1073]: [103.060] uds: sendto failed: No such file or directory
Apr 05 19:27:28 openeuler-riscv64 phc2sys[1073]: [104.064] uds: sendto failed: No such file or directory
Apr 05 19:27:29 openeuler-riscv64 phc2sys[1073]: [105.068] uds: sendto failed: No such file or directory
Apr 05 19:27:30 openeuler-riscv64 phc2sys[1073]: [106.072] uds: sendto failed: No such file or directory
Apr 05 19:27:31 openeuler-riscv64 phc2sys[1073]: [107.076] uds: sendto failed: No such file or directory
Apr 05 19:27:32 openeuler-riscv64 phc2sys[1073]: [108.080] uds: sendto failed: No such file or directory
Apr 05 19:27:33 openeuler-riscv64 phc2sys[1073]: [109.084] uds: sendto failed: No such file or directory
Apr 05 19:27:34 openeuler-riscv64 phc2sys[1073]: [110.088] uds: sendto failed: No such file or directory
Apr 05 19:27:35 openeuler-riscv64 phc2sys[1073]: [111.092] uds: sendto failed: No such file or directory
+ CHECK_RESULT 0 0 1 'There is an error message for the log of phc2sys.service'
+ actual_result=0
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of phc2sys.service'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 1 -eq 0 ']'
+ test 0x == 0x
+ test -n 'There is an error message for the log of phc2sys.service'
+ LOG_ERROR 'There is an error message for the log of phc2sys.service'
+ message='There is an error message for the log of phc2sys.service'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'There is an error message for the log of phc2sys.service'
Wed Apr  5 19:27:37 2023 - ERROR - There is an error message for the log of phc2sys.service
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 28'
+ message='../common/common_lib.sh line 28'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 28'
Wed Apr  5 19:27:37 2023 - ERROR - ../common/common_lib.sh line 28
+ '[' 0 -eq 1 ']'
+ return 0
+ test_reload phc2sys.service
+ service=phc2sys.service
+ systemctl start phc2sys.service
+ grep 'Job type reload is not applicable'
+ systemctl reload phc2sys.service
Failed to reload phc2sys.service: Job type reload is not applicable for unit phc2sys.service.
+ CHECK_RESULT 0 0 0 'Job type reload is not applicable for unit phc2sys.service'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Job type reload is not applicable for unit phc2sys.service'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl status phc2sys.service
+ grep 'Active: active'
     Active: active (running) since Wed 2023-04-05 19:27:20 CST; 18s ago
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Wed Apr  5 19:27:39 2023 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Apr  5 19:27:40 2023 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Wed Apr  5 19:27:40 2023 - INFO  - start environment cleanup.
+ systemctl stop phc2sys.service
+ systemctl stop ptp4l.service
+ sed -i 's\-f /etc/ptp4l.conf -i \-f /etc/ptp4l.conf -i eth0\g' /etc/sysconfig/ptp4l
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmp06sxxoc3 ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/GitRepo/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmp06sxxoc3
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Wed Apr  5 19:27:58 2023 - INFO  - Finish environment cleanup!
