+ source /root/GitRepo/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/GitRepo/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Wed Apr  5 11:23:09 2023 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL etcd
+ pkgs=etcd
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/GitRepo/mugen/libs/locallibs/rpm_manage.py install --pkgs etcd --node 1 --tempfile ''
Wed Apr  5 11:23:18 2023 - INFO  - pkgs:(etcd) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ systemctl start etcd
Job for etcd.service failed because the control process exited with error code.
See "systemctl status etcd.service" and "journalctl -xeu etcd.service" for details.
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Wed Apr  5 11:23:20 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Wed Apr  5 11:23:21 2023 - INFO  - Start to run test.
+ systemctl status etcd
+ grep 'active (running)'
+ CHECK_RESULT 1 0 0 'Check etcd.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcd.service start failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcd.service start failed'
+ LOG_ERROR 'Check etcd.service start failed'
+ message='Check etcd.service start failed'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcd.service start failed'
Wed Apr  5 11:23:22 2023 - ERROR - Check etcd.service start failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_03.sh line 29'
+ message='oe_test_etcd_03.sh line 29'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_03.sh line 29'
Wed Apr  5 11:23:23 2023 - ERROR - oe_test_etcd_03.sh line 29
+ '[' 0 -eq 1 ']'
+ return 0
+ expect
spawn etcdctl user add root
Password of root: 123456

Type password of root again for confirmation: 123456

+ grep 'User root created' etcd_log1
+ CHECK_RESULT 1 0 0 'Check etcdctl user add failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl user add failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcdctl user add failed.'
+ LOG_ERROR 'Check etcdctl user add failed.'
+ message='Check etcdctl user add failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcdctl user add failed.'
Wed Apr  5 11:23:39 2023 - ERROR - Check etcdctl user add failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_03.sh line 41'
+ message='oe_test_etcd_03.sh line 41'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_03.sh line 41'
Wed Apr  5 11:23:40 2023 - ERROR - oe_test_etcd_03.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ expect
spawn etcdctl user add test
Password of test: 123

Type password of test again for confirmation: 123

+ grep 'User test created' etcd_log2
+ CHECK_RESULT 1 0 0 'Check etcdctl user add failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl user add failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcdctl user add failed.'
+ LOG_ERROR 'Check etcdctl user add failed.'
+ message='Check etcdctl user add failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcdctl user add failed.'
Wed Apr  5 11:23:52 2023 - ERROR - Check etcdctl user add failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_03.sh line 52'
+ message='oe_test_etcd_03.sh line 52'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_03.sh line 52'
Wed Apr  5 11:23:53 2023 - ERROR - oe_test_etcd_03.sh line 52
+ '[' 0 -eq 1 ']'
+ return 0
+ etcdctl --endpoints=http://127.0.0.1:2379 auth enable
+ grep -i 'Authentication Enabled'
{"level":"warn","ts":"2023-04-05T11:23:58.639+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-4746b0ed-3fe9-4d3b-b790-a42c6af5dd8f/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
+ CHECK_RESULT 1 0 0 'Check etcdctl auth enable failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl auth enable failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcdctl auth enable failed.'
+ LOG_ERROR 'Check etcdctl auth enable failed.'
+ message='Check etcdctl auth enable failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcdctl auth enable failed.'
Wed Apr  5 11:23:59 2023 - ERROR - Check etcdctl auth enable failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_03.sh line 54'
+ message='oe_test_etcd_03.sh line 54'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_03.sh line 54'
Wed Apr  5 11:24:00 2023 - ERROR - oe_test_etcd_03.sh line 54
+ '[' 0 -eq 1 ']'
+ return 0
+ etcdctl role add role1 --user=root --password=123456
+ grep 'Role role1 created'
{"level":"warn","ts":"2023-04-05T11:24:02.942+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-c12da7db-aac2-4f5b-a383-0443fd64e776/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
+ CHECK_RESULT 1 0 0 'Check etcdctl role add failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl role add failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcdctl role add failed.'
+ LOG_ERROR 'Check etcdctl role add failed.'
+ message='Check etcdctl role add failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcdctl role add failed.'
Wed Apr  5 11:24:03 2023 - ERROR - Check etcdctl role add failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_03.sh line 56'
+ message='oe_test_etcd_03.sh line 56'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_03.sh line 56'
Wed Apr  5 11:24:04 2023 - ERROR - oe_test_etcd_03.sh line 56
+ '[' 0 -eq 1 ']'
+ return 0
+ etcdctl user grant-role test role1 --user=root --password=123456
+ grep 'Role role1 is granted to user test'
{"level":"warn","ts":"2023-04-05T11:24:06.850+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-ce0b18ba-0050-4ca7-8a93-78f65bd24ec9/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
+ CHECK_RESULT 1 0 0 'Check etcdctl user grant-role failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl user grant-role failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcdctl user grant-role failed.'
+ LOG_ERROR 'Check etcdctl user grant-role failed.'
+ message='Check etcdctl user grant-role failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcdctl user grant-role failed.'
Wed Apr  5 11:24:07 2023 - ERROR - Check etcdctl user grant-role failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_03.sh line 58'
+ message='oe_test_etcd_03.sh line 58'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_03.sh line 58'
Wed Apr  5 11:24:08 2023 - ERROR - oe_test_etcd_03.sh line 58
+ '[' 0 -eq 1 ']'
+ return 0
+ etcdctl role grant-permission role1 read a --user=root --password=123456
+ grep 'Role role1 updated'
{"level":"warn","ts":"2023-04-05T11:24:10.835+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-59217e93-3b6a-41f8-9d84-989616ae36ea/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
+ CHECK_RESULT 1 0 0 'Check etcdctl role grant-permission failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl role grant-permission failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcdctl role grant-permission failed.'
+ LOG_ERROR 'Check etcdctl role grant-permission failed.'
+ message='Check etcdctl role grant-permission failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcdctl role grant-permission failed.'
Wed Apr  5 11:24:11 2023 - ERROR - Check etcdctl role grant-permission failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_03.sh line 60'
+ message='oe_test_etcd_03.sh line 60'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_03.sh line 60'
Wed Apr  5 11:24:12 2023 - ERROR - oe_test_etcd_03.sh line 60
+ '[' 0 -eq 1 ']'
+ return 0
+ etcdctl --endpoints=http://127.0.0.1:2379 put a 123 --user=root --password=123456
+ grep OK
{"level":"warn","ts":"2023-04-05T11:24:14.698+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-683cdb6b-9797-4e64-a2fb-e8210dc9e0a7/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
+ CHECK_RESULT 1 0 0 'Check etcdctl put failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl put failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcdctl put failed.'
+ LOG_ERROR 'Check etcdctl put failed.'
+ message='Check etcdctl put failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcdctl put failed.'
Wed Apr  5 11:24:15 2023 - ERROR - Check etcdctl put failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_03.sh line 62'
+ message='oe_test_etcd_03.sh line 62'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_03.sh line 62'
Wed Apr  5 11:24:16 2023 - ERROR - oe_test_etcd_03.sh line 62
+ '[' 0 -eq 1 ']'
+ return 0
+ etcdctl get a --user=test:123
{"level":"warn","ts":"2023-04-05T11:24:18.563+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-080b2a4e-1cb5-40dd-b111-f64f3f690158/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
+ CHECK_RESULT 2 0 0 'Check etcdctl get --user failed.'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl get --user failed.'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'Check etcdctl get --user failed.'
+ LOG_ERROR 'Check etcdctl get --user failed.'
+ message='Check etcdctl get --user failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcdctl get --user failed.'
Wed Apr  5 11:24:19 2023 - ERROR - Check etcdctl get --user failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_03.sh line 64'
+ message='oe_test_etcd_03.sh line 64'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_03.sh line 64'
Wed Apr  5 11:24:20 2023 - ERROR - oe_test_etcd_03.sh line 64
+ '[' 0 -eq 1 ']'
+ return 0
+ etcdctl user list --user=root --password=123456
+ grep 'root\|test'
{"level":"warn","ts":"2023-04-05T11:24:22.614+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-075db75c-5703-4623-b6f8-362455d80733/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
+ CHECK_RESULT 1 0 0 'Check etcdctl user list failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl user list failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcdctl user list failed.'
+ LOG_ERROR 'Check etcdctl user list failed.'
+ message='Check etcdctl user list failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcdctl user list failed.'
Wed Apr  5 11:24:23 2023 - ERROR - Check etcdctl user list failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_03.sh line 66'
+ message='oe_test_etcd_03.sh line 66'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_03.sh line 66'
Wed Apr  5 11:24:24 2023 - ERROR - oe_test_etcd_03.sh line 66
+ '[' 0 -eq 1 ']'
+ return 0
+ etcdctl user delete test --user=root --password=123456
{"level":"warn","ts":"2023-04-05T11:24:26.438+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-61e98ca7-05e2-46ee-b73b-797fb0ad390b/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
+ CHECK_RESULT 2 0 0 'Check etcdctl user deletel failed.'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl user deletel failed.'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'Check etcdctl user deletel failed.'
+ LOG_ERROR 'Check etcdctl user deletel failed.'
+ message='Check etcdctl user deletel failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcdctl user deletel failed.'
Wed Apr  5 11:24:27 2023 - ERROR - Check etcdctl user deletel failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_03.sh line 68'
+ message='oe_test_etcd_03.sh line 68'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_03.sh line 68'
Wed Apr  5 11:24:27 2023 - ERROR - oe_test_etcd_03.sh line 68
+ '[' 0 -eq 1 ']'
+ return 0
+ etcdctl user list --user=root --password=123456
+ grep test
{"level":"warn","ts":"2023-04-05T11:24:30.366+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-ffc26360-1ebe-45dc-839a-39d9fbf40054/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
+ CHECK_RESULT 1 1 0 'Check etcdctl user deletel failed.'
+ actual_result=1
+ expect_result=1
+ mode=0
+ error_log='Check etcdctl user deletel failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 1x
+ return 0
+ etcdctl role delete role1 --user=root --password=123456
+ grep 'Role role1 deleted'
{"level":"warn","ts":"2023-04-05T11:24:32.847+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-9950e072-907d-4c03-879f-028d42035dbc/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
+ CHECK_RESULT 1 0 0 'Check etcdctl role deletel failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl role deletel failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcdctl role deletel failed.'
+ LOG_ERROR 'Check etcdctl role deletel failed.'
+ message='Check etcdctl role deletel failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcdctl role deletel failed.'
Wed Apr  5 11:24:33 2023 - ERROR - Check etcdctl role deletel failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_03.sh line 72'
+ message='oe_test_etcd_03.sh line 72'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_03.sh line 72'
Wed Apr  5 11:24:34 2023 - ERROR - oe_test_etcd_03.sh line 72
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'Authentication Disabled'
+ etcdctl --endpoints=http://127.0.0.1:2379 --user=root --password=123456 auth disable
{"level":"warn","ts":"2023-04-05T11:24:37.003+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-46abe25f-9149-4f25-b960-e05d0f085f0b/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
+ CHECK_RESULT 1 0 0 'Check etcdctl auth disable failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check etcdctl auth disable failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check etcdctl auth disable failed.'
+ LOG_ERROR 'Check etcdctl auth disable failed.'
+ message='Check etcdctl auth disable failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check etcdctl auth disable failed.'
Wed Apr  5 11:24:37 2023 - ERROR - Check etcdctl auth disable failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_etcd_03.sh line 74'
+ message='oe_test_etcd_03.sh line 74'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_etcd_03.sh line 74'
Wed Apr  5 11:24:38 2023 - ERROR - oe_test_etcd_03.sh line 74
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -i 'User root deleted'
+ etcdctl user del root
Wed Apr  5 11:53:06 2023 - ERROR - Timeout : Command 'bash -x oe_test_etcd_03.sh' timed out after 1799.9993164369998 seconds
