+ source ../common/common.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n function ']'
+ config_params
+ LOG_INFO 'Start to config params of the case.'
+ message='Start to config params of the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to config params of the case.'
Tue Nov 21 17:35:59 2023 - INFO  - Start to config params of the case.
++ mktemp -d -t nototools.XXXXXXXXXXXX
+ TMP_DIR=/tmp/nototools.fnbCfB4wsSYw
+ LOG_INFO 'End to config params of the case.'
+ message='End to config params of the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to config params of the case.'
Tue Nov 21 17:35:59 2023 - INFO  - End to config params of the case.
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Tue Nov 21 17:36:00 2023 - INFO  - Start to prepare the test environment.
+ common_pre
+ pip install -r ../common/requirements.txt
+ DNF_INSTALL 'nototools harfbuzz-devel cpio pango python3-gobject python3-cairo'
+ pkgs='nototools harfbuzz-devel cpio pango python3-gobject python3-cairo'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'nototools harfbuzz-devel cpio pango python3-gobject python3-cairo' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpm72zm7b2
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpm72zm7b2
+ notoconfig_pre
++ mktemp -d -t nototools.SRC.XXXXXXXXXXXX
+ TMP_SRCDIR=/tmp/nototools.SRC.aghFKbJZ5bCi
+ yumdownloader --source nototools --destdir /tmp/nototools.SRC.aghFKbJZ5bCi
No package nototools-0.2.17-1.oe2303.src available.
Exiting due to strict setting.
Error: No package nototools-0.2.17-1.oe2303.src available.
+ rpm2cpio '/tmp/nototools.SRC.aghFKbJZ5bCi/*.rpm'
+ cpio -div -D /tmp/nototools.SRC.aghFKbJZ5bCi
rpm2cpio: /tmp/nototools.SRC.aghFKbJZ5bCi/*.rpm: No such file or directory
+ tar -zxf '/tmp/nototools.SRC.aghFKbJZ5bCi/*.tar.gz' --strip-components 1 --directory /tmp/nototools.SRC.aghFKbJZ5bCi
tar (child): /tmp/nototools.SRC.aghFKbJZ5bCi/*.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
+ echo noto_tools=/tmp/nototools.SRC.aghFKbJZ5bCi
+ for src in "fonts" "cjk" "emoji"
+ echo noto_fonts=/tmp/nototools.SRC.aghFKbJZ5bCi/noto-fonts
+ for src in "fonts" "cjk" "emoji"
+ echo noto_cjk=/tmp/nototools.SRC.aghFKbJZ5bCi/noto-cjk
+ for src in "fonts" "cjk" "emoji"
+ echo noto_emoji=/tmp/nototools.SRC.aghFKbJZ5bCi/noto-emoji
+ mkdir -p /tmp/nototools.fnbCfB4wsSYw/test
+ cp -rf ./oe_test_nototools_base_create_image.sh ./sample_texts /tmp/nototools.fnbCfB4wsSYw
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Tue Nov 21 17:42:30 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Nov 21 17:42:30 2023 - INFO  - Start to run test.
+ create_image.py -h
+ grep -q usage
Traceback (most recent call last):
  File "/usr/bin/create_image.py", line 33, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: -h error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: -h error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: -h error'
+ LOG_ERROR 'option: -h error'
+ message='option: -h error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: -h error'
Tue Nov 21 17:42:32 2023 - ERROR - option: -h error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_create_image.sh line 51'
+ message='oe_test_nototools_base_create_image.sh line 51'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_create_image.sh line 51'
Tue Nov 21 17:42:32 2023 - ERROR - oe_test_nototools_base_create_image.sh line 51
+ '[' 0 -eq 1 ']'
+ return 0
+ create_image.py --help
+ grep -q usage
Traceback (most recent call last):
  File "/usr/bin/create_image.py", line 33, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --help error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --help error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --help error'
+ LOG_ERROR 'option: --help error'
+ message='option: --help error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --help error'
Tue Nov 21 17:42:33 2023 - ERROR - option: --help error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_create_image.sh line 53'
+ message='oe_test_nototools_base_create_image.sh line 53'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_create_image.sh line 53'
Tue Nov 21 17:42:34 2023 - ERROR - oe_test_nototools_base_create_image.sh line 53
+ '[' 0 -eq 1 ']'
+ return 0
+ cd /tmp/nototools.fnbCfB4wsSYw/test
+ create_image.py --test
Traceback (most recent call last):
  File "/usr/bin/create_image.py", line 33, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --test error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --test error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --test error'
+ LOG_ERROR 'option: --test error'
+ message='option: --test error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --test error'
Tue Nov 21 17:42:35 2023 - ERROR - option: --test error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_create_image.sh line 59'
+ message='oe_test_nototools_base_create_image.sh line 59'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_create_image.sh line 59'
Tue Nov 21 17:42:35 2023 - ERROR - oe_test_nototools_base_create_image.sh line 59
+ '[' 0 -eq 1 ']'
+ return 0
+ create_image.py --codes 1234 -f NotoNaskhArabic -b bold -i italic -st semi-condensed -s 16 -l ar -t png
Traceback (most recent call last):
  File "/usr/bin/create_image.py", line 33, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --codes 1234 -f NotoNaskhArabic -b bold -i italic -st semi-condensed -s 16 -l ar -t png error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --codes 1234 -f NotoNaskhArabic -b bold -i italic -st semi-condensed -s 16 -l ar -t png error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --codes 1234 -f NotoNaskhArabic -b bold -i italic -st semi-condensed -s 16 -l ar -t png error'
+ LOG_ERROR 'option: --codes 1234 -f NotoNaskhArabic -b bold -i italic -st semi-condensed -s 16 -l ar -t png error'
+ message='option: --codes 1234 -f NotoNaskhArabic -b bold -i italic -st semi-condensed -s 16 -l ar -t png error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --codes 1234 -f NotoNaskhArabic -b bold -i italic -st semi-condensed -s 16 -l ar -t png error'
Tue Nov 21 17:42:36 2023 - ERROR - option: --codes 1234 -f NotoNaskhArabic -b bold -i italic -st semi-condensed -s 16 -l ar -t png error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_create_image.sh line 64'
+ message='oe_test_nototools_base_create_image.sh line 64'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_create_image.sh line 64'
Tue Nov 21 17:42:37 2023 - ERROR - oe_test_nototools_base_create_image.sh line 64
+ '[' 0 -eq 1 ']'
+ return 0
+ create_image.py --codes 1234 -f NotoNasJPArabic -b heavy -i oblique -st ultra-expanded -s 8 -l JP -t svg
Traceback (most recent call last):
  File "/usr/bin/create_image.py", line 33, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --codes 1234 -f NotoNasJPArabic -b heavy -i oblique -st ultra-expanded -s 8 -l JP -t svg error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --codes 1234 -f NotoNasJPArabic -b heavy -i oblique -st ultra-expanded -s 8 -l JP -t svg error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --codes 1234 -f NotoNasJPArabic -b heavy -i oblique -st ultra-expanded -s 8 -l JP -t svg error'
+ LOG_ERROR 'option: --codes 1234 -f NotoNasJPArabic -b heavy -i oblique -st ultra-expanded -s 8 -l JP -t svg error'
+ message='option: --codes 1234 -f NotoNasJPArabic -b heavy -i oblique -st ultra-expanded -s 8 -l JP -t svg error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --codes 1234 -f NotoNasJPArabic -b heavy -i oblique -st ultra-expanded -s 8 -l JP -t svg error'
Tue Nov 21 17:42:38 2023 - ERROR - option: --codes 1234 -f NotoNasJPArabic -b heavy -i oblique -st ultra-expanded -s 8 -l JP -t svg error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_create_image.sh line 67'
+ message='oe_test_nototools_base_create_image.sh line 67'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_create_image.sh line 67'
Tue Nov 21 17:42:38 2023 - ERROR - oe_test_nototools_base_create_image.sh line 67
+ '[' 0 -eq 1 ']'
+ return 0
+ create_image.py --codes 1234 -f NotoNas -b normal -i normal -st semi-expanded -s 8 -l mn -t png
Traceback (most recent call last):
  File "/usr/bin/create_image.py", line 33, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --codes 1234 -f NotoNas -b normal -i normal -st semi-expanded -s 8 -l mn -t png error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --codes 1234 -f NotoNas -b normal -i normal -st semi-expanded -s 8 -l mn -t png error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --codes 1234 -f NotoNas -b normal -i normal -st semi-expanded -s 8 -l mn -t png error'
+ LOG_ERROR 'option: --codes 1234 -f NotoNas -b normal -i normal -st semi-expanded -s 8 -l mn -t png error'
+ message='option: --codes 1234 -f NotoNas -b normal -i normal -st semi-expanded -s 8 -l mn -t png error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --codes 1234 -f NotoNas -b normal -i normal -st semi-expanded -s 8 -l mn -t png error'
Tue Nov 21 17:42:40 2023 - ERROR - option: --codes 1234 -f NotoNas -b normal -i normal -st semi-expanded -s 8 -l mn -t png error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_create_image.sh line 70'
+ message='oe_test_nototools_base_create_image.sh line 70'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_create_image.sh line 70'
Tue Nov 21 17:42:40 2023 - ERROR - oe_test_nototools_base_create_image.sh line 70
+ '[' 0 -eq 1 ']'
+ return 0
+ create_image.py --codes 1234 -f NotoNas -b bold -i italic -st extra-expanded -s 16 -l ar -t svg
Traceback (most recent call last):
  File "/usr/bin/create_image.py", line 33, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --codes 1234 -f NotoNas -b bold -i italic -st extra-expanded -s 16 -l ar -t svg error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --codes 1234 -f NotoNas -b bold -i italic -st extra-expanded -s 16 -l ar -t svg error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --codes 1234 -f NotoNas -b bold -i italic -st extra-expanded -s 16 -l ar -t svg error'
+ LOG_ERROR 'option: --codes 1234 -f NotoNas -b bold -i italic -st extra-expanded -s 16 -l ar -t svg error'
+ message='option: --codes 1234 -f NotoNas -b bold -i italic -st extra-expanded -s 16 -l ar -t svg error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --codes 1234 -f NotoNas -b bold -i italic -st extra-expanded -s 16 -l ar -t svg error'
Tue Nov 21 17:42:41 2023 - ERROR - option: --codes 1234 -f NotoNas -b bold -i italic -st extra-expanded -s 16 -l ar -t svg error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_create_image.sh line 73'
+ message='oe_test_nototools_base_create_image.sh line 73'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_create_image.sh line 73'
Tue Nov 21 17:42:42 2023 - ERROR - oe_test_nototools_base_create_image.sh line 73
+ '[' 0 -eq 1 ']'
+ return 0
+ create_image.py --codes 1234 --font NotoNaskhArabic --bold bold --italic italic --stretch semi-condensed --size 16 --lang ar --type png
Traceback (most recent call last):
  File "/usr/bin/create_image.py", line 33, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --codes 1234 --font NotoNaskhArabic --bold bold --italic italic --stretch semi-condensed --size 16 --lang ar --type png error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --codes 1234 --font NotoNaskhArabic --bold bold --italic italic --stretch semi-condensed --size 16 --lang ar --type png error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --codes 1234 --font NotoNaskhArabic --bold bold --italic italic --stretch semi-condensed --size 16 --lang ar --type png error'
+ LOG_ERROR 'option: --codes 1234 --font NotoNaskhArabic --bold bold --italic italic --stretch semi-condensed --size 16 --lang ar --type png error'
+ message='option: --codes 1234 --font NotoNaskhArabic --bold bold --italic italic --stretch semi-condensed --size 16 --lang ar --type png error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --codes 1234 --font NotoNaskhArabic --bold bold --italic italic --stretch semi-condensed --size 16 --lang ar --type png error'
Tue Nov 21 17:42:43 2023 - ERROR - option: --codes 1234 --font NotoNaskhArabic --bold bold --italic italic --stretch semi-condensed --size 16 --lang ar --type png error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_create_image.sh line 76'
+ message='oe_test_nototools_base_create_image.sh line 76'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_create_image.sh line 76'
Tue Nov 21 17:42:43 2023 - ERROR - oe_test_nototools_base_create_image.sh line 76
+ '[' 0 -eq 1 ']'
+ return 0
+ create_image.py --text 1234 -f NotoNaskhArabic -b ultralight -i italic -st ultra-condensed -s 16 -l ar -t png
Traceback (most recent call last):
  File "/usr/bin/create_image.py", line 33, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --text 1234 -f NotoNaskhArabic -b ultralight -i italic -st ultra-condensed -s 16 -l ar -t png error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --text 1234 -f NotoNaskhArabic -b ultralight -i italic -st ultra-condensed -s 16 -l ar -t png error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --text 1234 -f NotoNaskhArabic -b ultralight -i italic -st ultra-condensed -s 16 -l ar -t png error'
+ LOG_ERROR 'option: --text 1234 -f NotoNaskhArabic -b ultralight -i italic -st ultra-condensed -s 16 -l ar -t png error'
+ message='option: --text 1234 -f NotoNaskhArabic -b ultralight -i italic -st ultra-condensed -s 16 -l ar -t png error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --text 1234 -f NotoNaskhArabic -b ultralight -i italic -st ultra-condensed -s 16 -l ar -t png error'
Tue Nov 21 17:42:44 2023 - ERROR - option: --text 1234 -f NotoNaskhArabic -b ultralight -i italic -st ultra-condensed -s 16 -l ar -t png error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_create_image.sh line 81'
+ message='oe_test_nototools_base_create_image.sh line 81'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_create_image.sh line 81'
Tue Nov 21 17:42:45 2023 - ERROR - oe_test_nototools_base_create_image.sh line 81
+ '[' 0 -eq 1 ']'
+ return 0
+ create_image.py --text 1234 -f NotoNasJPArabic -b light -i oblique -st extra-condensed -s 8 -l JP -t svg
Traceback (most recent call last):
  File "/usr/bin/create_image.py", line 33, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --text 1234 -f NotoNasJPArabic -b light -i oblique -st extra-condensed -s 8 -l JP -t svg error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --text 1234 -f NotoNasJPArabic -b light -i oblique -st extra-condensed -s 8 -l JP -t svg error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --text 1234 -f NotoNasJPArabic -b light -i oblique -st extra-condensed -s 8 -l JP -t svg error'
+ LOG_ERROR 'option: --text 1234 -f NotoNasJPArabic -b light -i oblique -st extra-condensed -s 8 -l JP -t svg error'
+ message='option: --text 1234 -f NotoNasJPArabic -b light -i oblique -st extra-condensed -s 8 -l JP -t svg error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --text 1234 -f NotoNasJPArabic -b light -i oblique -st extra-condensed -s 8 -l JP -t svg error'
Tue Nov 21 17:42:46 2023 - ERROR - option: --text 1234 -f NotoNasJPArabic -b light -i oblique -st extra-condensed -s 8 -l JP -t svg error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_create_image.sh line 84'
+ message='oe_test_nototools_base_create_image.sh line 84'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_create_image.sh line 84'
Tue Nov 21 17:42:47 2023 - ERROR - oe_test_nototools_base_create_image.sh line 84
+ '[' 0 -eq 1 ']'
+ return 0
+ create_image.py --text 1234 -f NotoNas -b normal -i normal -st condensed -s 8 -l mn -t png -mh -2 -hm 16
Traceback (most recent call last):
  File "/usr/bin/create_image.py", line 33, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --text 1234 -f NotoNas -b normal -i normal -st condensed -s 8 -l mn -t png -mh -2 -hm 16 error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --text 1234 -f NotoNas -b normal -i normal -st condensed -s 8 -l mn -t png -mh -2 -hm 16 error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --text 1234 -f NotoNas -b normal -i normal -st condensed -s 8 -l mn -t png -mh -2 -hm 16 error'
+ LOG_ERROR 'option: --text 1234 -f NotoNas -b normal -i normal -st condensed -s 8 -l mn -t png -mh -2 -hm 16 error'
+ message='option: --text 1234 -f NotoNas -b normal -i normal -st condensed -s 8 -l mn -t png -mh -2 -hm 16 error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --text 1234 -f NotoNas -b normal -i normal -st condensed -s 8 -l mn -t png -mh -2 -hm 16 error'
Tue Nov 21 17:42:48 2023 - ERROR - option: --text 1234 -f NotoNas -b normal -i normal -st condensed -s 8 -l mn -t png -mh -2 -hm 16 error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_create_image.sh line 87'
+ message='oe_test_nototools_base_create_image.sh line 87'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_create_image.sh line 87'
Tue Nov 21 17:42:48 2023 - ERROR - oe_test_nototools_base_create_image.sh line 87
+ '[' 0 -eq 1 ']'
+ return 0
+ create_image.py --text 1234 -f NotoNas -b bold -i italic -st normal -s 16 -l ar -t svg -mh -2 -hm 16
Traceback (most recent call last):
  File "/usr/bin/create_image.py", line 33, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --text 1234 -f NotoNas -b bold -i italic -st normal -s 16 -l ar -t svg -mh -2 -hm 16 error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --text 1234 -f NotoNas -b bold -i italic -st normal -s 16 -l ar -t svg -mh -2 -hm 16 error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --text 1234 -f NotoNas -b bold -i italic -st normal -s 16 -l ar -t svg -mh -2 -hm 16 error'
+ LOG_ERROR 'option: --text 1234 -f NotoNas -b bold -i italic -st normal -s 16 -l ar -t svg -mh -2 -hm 16 error'
+ message='option: --text 1234 -f NotoNas -b bold -i italic -st normal -s 16 -l ar -t svg -mh -2 -hm 16 error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --text 1234 -f NotoNas -b bold -i italic -st normal -s 16 -l ar -t svg -mh -2 -hm 16 error'
Tue Nov 21 17:42:49 2023 - ERROR - option: --text 1234 -f NotoNas -b bold -i italic -st normal -s 16 -l ar -t svg -mh -2 -hm 16 error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_create_image.sh line 90'
+ message='oe_test_nototools_base_create_image.sh line 90'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_create_image.sh line 90'
Tue Nov 21 17:42:50 2023 - ERROR - oe_test_nototools_base_create_image.sh line 90
+ '[' 0 -eq 1 ']'
+ return 0
+ create_image.py --text 1234 --font NotoNas --bold bold --italic italic --stretch normal --size 16 --lang ar --type svg --maxheight -2 --horiz_margin 16
Traceback (most recent call last):
  File "/usr/bin/create_image.py", line 33, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --text 1234 --font NotoNas --bold bold --italic italic --stretch normal --size 16 --lang ar --type svg --maxheight -2 --horiz_margin 16 error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --text 1234 --font NotoNas --bold bold --italic italic --stretch normal --size 16 --lang ar --type svg --maxheight -2 --horiz_margin 16 error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --text 1234 --font NotoNas --bold bold --italic italic --stretch normal --size 16 --lang ar --type svg --maxheight -2 --horiz_margin 16 error'
+ LOG_ERROR 'option: --text 1234 --font NotoNas --bold bold --italic italic --stretch normal --size 16 --lang ar --type svg --maxheight -2 --horiz_margin 16 error'
+ message='option: --text 1234 --font NotoNas --bold bold --italic italic --stretch normal --size 16 --lang ar --type svg --maxheight -2 --horiz_margin 16 error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --text 1234 --font NotoNas --bold bold --italic italic --stretch normal --size 16 --lang ar --type svg --maxheight -2 --horiz_margin 16 error'
Tue Nov 21 17:42:51 2023 - ERROR - option: --text 1234 --font NotoNas --bold bold --italic italic --stretch normal --size 16 --lang ar --type svg --maxheight -2 --horiz_margin 16 error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_create_image.sh line 93'
+ message='oe_test_nototools_base_create_image.sh line 93'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_create_image.sh line 93'
Tue Nov 21 17:42:51 2023 - ERROR - oe_test_nototools_base_create_image.sh line 93
+ '[' 0 -eq 1 ']'
+ return 0
+ create_image.py --out output.svg --text 123
Traceback (most recent call last):
  File "/usr/bin/create_image.py", line 33, in <module>
    import pango
ModuleNotFoundError: No module named 'pango'
+ CHECK_RESULT 1 0 0 'option: --out error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='option: --out error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'option: --out error'
+ LOG_ERROR 'option: --out error'
+ message='option: --out error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'option: --out error'
Tue Nov 21 17:42:52 2023 - ERROR - option: --out error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_nototools_base_create_image.sh line 98'
+ message='oe_test_nototools_base_create_image.sh line 98'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_nototools_base_create_image.sh line 98'
Tue Nov 21 17:42:53 2023 - ERROR - oe_test_nototools_base_create_image.sh line 98
+ '[' 0 -eq 1 ']'
+ return 0
+ cd -
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Nov 21 17:42:54 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 14
+ test 14 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Nov 21 17:42:54 2023 - ERROR - failed to execute the case.
+ exit 14
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Nov 21 17:42:55 2023 - INFO  - Start to restore the test environment.
+ rm -rf /tmp/nototools.fnbCfB4wsSYw
+ common_post
+ rm -rf /tmp/nototools.SRC.aghFKbJZ5bCi /root/.notoconfig
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpm72zm7b2 ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpm72zm7b2
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Nov 21 17:44:02 2023 - INFO  - End to restore the test environment.
