+ source ../common/storage_disk_lib.sh
++ source /root/GitRepo/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/GitRepo/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Thu Apr  6 14:33:21 2023 - INFO  - Start environment preparation.
+ check_free_disk
++ TEST_DISK
++ id=1
++ python3 /root/GitRepo/mugen/libs/locallibs/get_test_device.py --device disk --node 1
+ disks=vdb
+ disk_list=($disks)
+ local_disk=vdb
+ local_disk1=
+ local_disk2=
+ local_disk3=
+ mkfs.ext4 -F /dev/vdb
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:      0/512000             done                            
Creating filesystem with 512000 1k blocks and 128016 inodes
Filesystem UUID: f8405926-070c-4b4c-829d-df2e7e1f24db
Superblock backups stored on blocks: 
	8193, 24577, 40961, 57345, 73729, 204801, 221185, 401409

Allocating group tables:  0/63     done                            
Writing inode tables:  0/63     done                            
Creating journal (8192 blocks): done
Writing superblocks and filesystem accounting information:  0/63     done

+ mkfs.ext4 -F /dev/
mke2fs 1.46.5 (30-Dec-2021)
mkfs.ext4: Device size reported to be zero.  Invalid partition specified, or
	partition table wasn't reread after running fdisk, due to
	a modified partition being busy and in use.  You may need to reboot
	to re-read your partition table.

+ mkfs.ext4 -F /dev/
mke2fs 1.46.5 (30-Dec-2021)
mkfs.ext4: Device size reported to be zero.  Invalid partition specified, or
	partition table wasn't reread after running fdisk, due to
	a modified partition being busy and in use.  You may need to reboot
	to re-read your partition table.

+ mkfs.ext4 -F /dev/
mke2fs 1.46.5 (30-Dec-2021)
mkfs.ext4: Device size reported to be zero.  Invalid partition specified, or
	partition table wasn't reread after running fdisk, due to
	a modified partition being busy and in use.  You may need to reboot
	to re-read your partition table.

+ pvcreate /dev/ -y
  No device found for /dev/.
+ vgcreate openeulertest /dev/ -y
  No device found for /dev/.
+ LOG_INFO 'Environmental preparation is over.'
+ message='Environmental preparation is over.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Environmental preparation is over.'
Thu Apr  6 14:33:32 2023 - INFO  - Environmental preparation is over.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase!'
+ message='Start executing testcase!'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase!'
Thu Apr  6 14:33:33 2023 - INFO  - Start executing testcase!
+ vgextend openeulertest /dev/vdb -y
  Wiping ext4 signature on /dev/vdb.
  Physical volume "/dev/vdb" successfully created.
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
+ vgextend openeulertest /dev/ -y
  No device found for /dev/.
+ vgextend openeulertest /dev/ -y
  No device found for /dev/.
+ expect -c '
    set timeout 30
    log_file testlog
    spawn lvcreate --type raid1 -m 1 -L 50MB -n test openeulertest -y
    expect "*\[y/n\]*" {send "y\r"}
    expect eof
'
spawn lvcreate --type raid1 -m 1 -L 50MB -n test openeulertest -y
modprobe: FATAL: Module dm-raid not found in directory /lib/modules/6.1.8-3.oe2303.riscv64
y
  /usr/sbin/modprobe failed: 1
  raid1: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.
+ grep -iE 'while executing|error|fail' testlog
  /usr/sbin/modprobe failed: 1
+ CHECK_RESULT 0 1
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_create_raid.sh line 46'
+ message='oe_test_storage_lvm_create_raid.sh line 46'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_create_raid.sh line 46'
Thu Apr  6 14:33:36 2023 - ERROR - oe_test_storage_lvm_create_raid.sh line 46
+ '[' 0 -eq 1 ']'
+ return 0
+ expect -c '
    set timeout 30
    log_file testlog1
    spawn lvcreate --type raid5 -i 3 -L 50MB -n test1 openeulertest -y
    expect "*\[y/n\]*" {send "y\r"}
    expect eof
'
spawn lvcreate --type raid5 -i 3 -L 50MB -n test1 openeulertest -y
modprobe: FATAL: Module dm-raid not found in directory /lib/modules/6.1.8-3.oe2303.riscv64
y
  /usr/sbin/modprobe failed: 1
  raid5: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.
+ grep -iE 'while executing|error|fail' testlog1
  /usr/sbin/modprobe failed: 1
+ CHECK_RESULT 0 1
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_create_raid.sh line 55'
+ message='oe_test_storage_lvm_create_raid.sh line 55'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_create_raid.sh line 55'
Thu Apr  6 14:33:37 2023 - ERROR - oe_test_storage_lvm_create_raid.sh line 55
+ '[' 0 -eq 1 ']'
+ return 0
+ expect -c '
    set timeout 30
    log_file testlog2
    spawn lvcreate -y --type raid5 -i 3 -L 50MB -n test2 openeulertest
    expect "*\[y/n\]*" {send "y\r"}
    expect eof
'
spawn lvcreate -y --type raid5 -i 3 -L 50MB -n test2 openeulertest
modprobe: FATAL: Module dm-raid not found in directory /lib/modules/6.1.8-3.oe2303.riscv64
y
  /usr/sbin/modprobe failed: 1
  raid5: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.
+ grep -iE 'while executing|error|fail' testlog2
  /usr/sbin/modprobe failed: 1
+ CHECK_RESULT 0 1
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_create_raid.sh line 64'
+ message='oe_test_storage_lvm_create_raid.sh line 64'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_create_raid.sh line 64'
Thu Apr  6 14:33:39 2023 - ERROR - oe_test_storage_lvm_create_raid.sh line 64
+ '[' 0 -eq 1 ']'
+ return 0
+ grep /dev/openeulertest/test
+ lvscan
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_create_raid.sh line 66'
+ message='oe_test_storage_lvm_create_raid.sh line 66'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_create_raid.sh line 66'
Thu Apr  6 14:33:40 2023 - ERROR - oe_test_storage_lvm_create_raid.sh line 66
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End of testcase execution!'
+ message='End of testcase execution!'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'End of testcase execution!'
Thu Apr  6 14:33:41 2023 - INFO  - End of testcase execution!
+ CASE_RESULT 0
+ case_re=0
+ test -z 4
+ test 4 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Apr  6 14:33:41 2023 - ERROR - failed to execute the case.
+ exit 4
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Thu Apr  6 14:33:42 2023 - INFO  - start environment cleanup.
+ lvremove openeulertest/test openeulertest/test1 openeulertest/test2 -y
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
+ vgremove openeulertest -y
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
+ pvremove /dev/ /dev/ /dev/vdb /dev/
  No device found for /dev/.
  No device found for /dev/.
  No device found for /dev/.
  Labels on physical volume "/dev/vdb" successfully wiped.
+ rm -rf testlog testlog1 testlog2
+ LOG_INFO 'Finish environment cleanup.'
+ message='Finish environment cleanup.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Thu Apr  6 14:33:44 2023 - INFO  - Finish environment cleanup.
