+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment'
+ message='Start to prepare the test environment'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment'
Tue Nov 21 22:41:00 2023 - INFO  - Start to prepare the test environment
+ DNF_INSTALL pylint
+ pkgs=pylint
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs pylint --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpqcl_lhqu
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpqcl_lhqu
+ LOG_INFO 'End to prepare the test environment'
+ message='End to prepare the test environment'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment'
Tue Nov 21 22:41:46 2023 - INFO  - End to prepare the test environment
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Nov 21 22:41:46 2023 - INFO  - Start to run test.
+ pylint -h
+ grep Usage
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L31: -h No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L31: -h No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L31: -h No Pass'
+ LOG_ERROR 'L31: -h No Pass'
+ message='L31: -h No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L31: -h No Pass'
Tue Nov 21 22:41:53 2023 - ERROR - L31: -h No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_01.sh line 31'
+ message='oe_test_pylint_01.sh line 31'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_01.sh line 31'
Tue Nov 21 22:41:54 2023 - ERROR - oe_test_pylint_01.sh line 31
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint --long-help
+ grep Usage
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L33: -long-help No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L33: -long-help No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L33: -long-help No Pass'
+ LOG_ERROR 'L33: -long-help No Pass'
+ message='L33: -long-help No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L33: -long-help No Pass'
Tue Nov 21 22:42:00 2023 - ERROR - L33: -long-help No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_01.sh line 33'
+ message='oe_test_pylint_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_01.sh line 33'
Tue Nov 21 22:42:01 2023 - ERROR - oe_test_pylint_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint '--init-hook=import sys; import os; sys.path.append(os.getcwd())' ./common/test.py
+ grep 'Module test'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L35: pylint --init-hook <code> No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L35: pylint --init-hook <code> No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L35: pylint --init-hook <code> No Pass'
+ LOG_ERROR 'L35: pylint --init-hook <code> No Pass'
+ message='L35: pylint --init-hook <code> No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L35: pylint --init-hook <code> No Pass'
Tue Nov 21 22:42:07 2023 - ERROR - L35: pylint --init-hook <code> No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_01.sh line 35'
+ message='oe_test_pylint_01.sh line 35'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_01.sh line 35'
Tue Nov 21 22:42:08 2023 - ERROR - oe_test_pylint_01.sh line 35
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint -E ./common/test_error.py
+ grep 'Module test'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L37: pylint -E No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L37: pylint -E No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L37: pylint -E No Pass'
+ LOG_ERROR 'L37: pylint -E No Pass'
+ message='L37: pylint -E No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L37: pylint -E No Pass'
Tue Nov 21 22:42:14 2023 - ERROR - L37: pylint -E No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_01.sh line 37'
+ message='oe_test_pylint_01.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_01.sh line 37'
Tue Nov 21 22:42:15 2023 - ERROR - oe_test_pylint_01.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'Your code has been rated at'
+ pylint --py3k ./common/test.py
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L39: pylint --py3k No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L39: pylint --py3k No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L39: pylint --py3k No Pass'
+ LOG_ERROR 'L39: pylint --py3k No Pass'
+ message='L39: pylint --py3k No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L39: pylint --py3k No Pass'
Tue Nov 21 22:42:21 2023 - ERROR - L39: pylint --py3k No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_01.sh line 39'
+ message='oe_test_pylint_01.sh line 39'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_01.sh line 39'
Tue Nov 21 22:42:22 2023 - ERROR - oe_test_pylint_01.sh line 39
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint -v ./common/test.py
+ grep 'Module test'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L41: pylint -v No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L41: pylint -v No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L41: pylint -v No Pass'
+ LOG_ERROR 'L41: pylint -v No Pass'
+ message='L41: pylint -v No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L41: pylint -v No Pass'
Tue Nov 21 22:42:29 2023 - ERROR - L41: pylint -v No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_01.sh line 41'
+ message='oe_test_pylint_01.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_01.sh line 41'
Tue Nov 21 22:42:29 2023 - ERROR - oe_test_pylint_01.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint --verbose ./common/test.py
+ grep 'Module test'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L43: pylint --verbose No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L43: pylint --verbose No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L43: pylint --verbose No Pass'
+ LOG_ERROR 'L43: pylint --verbose No Pass'
+ message='L43: pylint --verbose No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L43: pylint --verbose No Pass'
Tue Nov 21 22:42:36 2023 - ERROR - L43: pylint --verbose No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_01.sh line 43'
+ message='oe_test_pylint_01.sh line 43'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_01.sh line 43'
Tue Nov 21 22:42:37 2023 - ERROR - oe_test_pylint_01.sh line 43
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint --ignore=CVS --generate-rcfile
+ grep ignore=CVS
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L45: pylint --ignore No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L45: pylint --ignore No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L45: pylint --ignore No Pass'
+ LOG_ERROR 'L45: pylint --ignore No Pass'
+ message='L45: pylint --ignore No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L45: pylint --ignore No Pass'
Tue Nov 21 22:42:43 2023 - ERROR - L45: pylint --ignore No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_01.sh line 45'
+ message='oe_test_pylint_01.sh line 45'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_01.sh line 45'
Tue Nov 21 22:42:43 2023 - ERROR - oe_test_pylint_01.sh line 45
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint --ignore-patterns test.py --generate-rcfile
+ grep ignore-patterns=test.py
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L47: pylint --ignore-patterns No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L47: pylint --ignore-patterns No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L47: pylint --ignore-patterns No Pass'
+ LOG_ERROR 'L47: pylint --ignore-patterns No Pass'
+ message='L47: pylint --ignore-patterns No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L47: pylint --ignore-patterns No Pass'
Tue Nov 21 22:42:49 2023 - ERROR - L47: pylint --ignore-patterns No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_01.sh line 47'
+ message='oe_test_pylint_01.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_01.sh line 47'
Tue Nov 21 22:42:50 2023 - ERROR - oe_test_pylint_01.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ pylint --persistent=n --generate-rcfile
+ grep persistent=no
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 21, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.10/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.parallel import check_parallel
  File "/usr/lib/python3.10/site-packages/pylint/lint/parallel.py", line 8, in <module>
    from pylint import reporters
  File "/usr/lib/python3.10/site-packages/pylint/reporters/__init__.py", line 27, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L49: pylint --persistent <y_or_n> No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L49: pylint --persistent <y_or_n> No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L49: pylint --persistent <y_or_n> No Pass'
+ LOG_ERROR 'L49: pylint --persistent <y_or_n> No Pass'
+ message='L49: pylint --persistent <y_or_n> No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L49: pylint --persistent <y_or_n> No Pass'
Tue Nov 21 22:42:57 2023 - ERROR - L49: pylint --persistent <y_or_n> No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pylint_01.sh line 49'
+ message='oe_test_pylint_01.sh line 49'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pylint_01.sh line 49'
Tue Nov 21 22:42:57 2023 - ERROR - oe_test_pylint_01.sh line 49
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Nov 21 22:42:58 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 10
+ test 10 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Nov 21 22:42:58 2023 - ERROR - failed to execute the case.
+ exit 10
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Nov 21 22:42:59 2023 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpqcl_lhqu ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpqcl_lhqu
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Nov 21 22:43:11 2023 - INFO  - End to restore the test environment.
