+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment'
+ message='Start to prepare the test environment'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment'
Tue Nov 21 22:58:24 2023 - INFO  - Start to prepare the test environment
+ DNF_INSTALL pylint
+ pkgs=pylint
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs pylint --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpx_u824pi
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpx_u824pi
+ LOG_INFO 'End to prepare the test environment'
+ message='End to prepare the test environment'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment'
Tue Nov 21 22:59:13 2023 - INFO  - End to prepare the test environment
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Nov 21 22:59:14 2023 - INFO  - Start to run test.
+ pyreverse -h
+ grep -E pyreverse
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pyreverse", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pyreverse')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 37, in run_pyreverse
    from pylint.pyreverse.main import Run as PyreverseRun
  File "/usr/lib/python3.10/site-packages/pylint/pyreverse/main.py", line 31, in <module>
    from pylint.config import ConfigurationMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/__init__.py", line 43, in <module>
    from pylint.config.configuration_mixin import ConfigurationMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/configuration_mixin.py", line 4, in <module>
    from pylint.config.option_manager_mixin import OptionsManagerMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/option_manager_mixin.py", line 19, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L31: -h No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L31: -h No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L31: -h No Pass'
+ LOG_ERROR 'L31: -h No Pass'
+ message='L31: -h No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L31: -h No Pass'
Tue Nov 21 22:59:20 2023 - ERROR - L31: -h No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pyreverse_01.sh line 31'
+ message='oe_test_pyreverse_01.sh line 31'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pyreverse_01.sh line 31'
Tue Nov 21 22:59:21 2023 - ERROR - oe_test_pyreverse_01.sh line 31
+ '[' 0 -eq 1 ']'
+ return 0
+ pyreverse --help
+ grep -E pyreverse
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pyreverse", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pyreverse')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 37, in run_pyreverse
    from pylint.pyreverse.main import Run as PyreverseRun
  File "/usr/lib/python3.10/site-packages/pylint/pyreverse/main.py", line 31, in <module>
    from pylint.config import ConfigurationMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/__init__.py", line 43, in <module>
    from pylint.config.configuration_mixin import ConfigurationMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/configuration_mixin.py", line 4, in <module>
    from pylint.config.option_manager_mixin import OptionsManagerMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/option_manager_mixin.py", line 19, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ CHECK_RESULT 1 0 0 'L33: -help No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L33: -help No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L33: -help No Pass'
+ LOG_ERROR 'L33: -help No Pass'
+ message='L33: -help No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L33: -help No Pass'
Tue Nov 21 22:59:27 2023 - ERROR - L33: -help No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pyreverse_01.sh line 33'
+ message='oe_test_pyreverse_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pyreverse_01.sh line 33'
Tue Nov 21 22:59:28 2023 - ERROR - oe_test_pyreverse_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ pyreverse --filter-mode PUB_ONLY string
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pyreverse", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pyreverse')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 37, in run_pyreverse
    from pylint.pyreverse.main import Run as PyreverseRun
  File "/usr/lib/python3.10/site-packages/pylint/pyreverse/main.py", line 31, in <module>
    from pylint.config import ConfigurationMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/__init__.py", line 43, in <module>
    from pylint.config.configuration_mixin import ConfigurationMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/configuration_mixin.py", line 4, in <module>
    from pylint.config.option_manager_mixin import OptionsManagerMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/option_manager_mixin.py", line 19, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ grep classes.dot
+ find . -name classes.dot
+ rm -rf classes.dot
+ CHECK_RESULT 0 0 0 'L37: --filter-mode No Pass'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='L37: --filter-mode No Pass'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ pyreverse -f PUB_ONLY string
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pyreverse", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pyreverse')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 37, in run_pyreverse
    from pylint.pyreverse.main import Run as PyreverseRun
  File "/usr/lib/python3.10/site-packages/pylint/pyreverse/main.py", line 31, in <module>
    from pylint.config import ConfigurationMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/__init__.py", line 43, in <module>
    from pylint.config.configuration_mixin import ConfigurationMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/configuration_mixin.py", line 4, in <module>
    from pylint.config.option_manager_mixin import OptionsManagerMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/option_manager_mixin.py", line 19, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ grep classes.dot
+ find . -name classes.dot
+ rm -rf classes.dot
+ CHECK_RESULT 0 0 0 'L41: -f No Pass'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='L41: -f No Pass'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ pyreverse --class pylint.checkers.classes.ClassChecker pylint
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pyreverse", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pyreverse')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 37, in run_pyreverse
    from pylint.pyreverse.main import Run as PyreverseRun
  File "/usr/lib/python3.10/site-packages/pylint/pyreverse/main.py", line 31, in <module>
    from pylint.config import ConfigurationMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/__init__.py", line 43, in <module>
    from pylint.config.configuration_mixin import ConfigurationMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/configuration_mixin.py", line 4, in <module>
    from pylint.config.option_manager_mixin import OptionsManagerMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/option_manager_mixin.py", line 19, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ grep pylint.checkers.classes.ClassChecker.dot
+ find . -name pylint.checkers.classes.ClassChecker.dot
+ rm -rf pylint.checkers.classes.ClassChecker.dot
+ CHECK_RESULT 0 0 0 'L45: -class No Pass'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='L45: -class No Pass'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ pyreverse -c pylint.checkers.classes.ClassChecker pylint
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pyreverse", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pyreverse')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 37, in run_pyreverse
    from pylint.pyreverse.main import Run as PyreverseRun
  File "/usr/lib/python3.10/site-packages/pylint/pyreverse/main.py", line 31, in <module>
    from pylint.config import ConfigurationMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/__init__.py", line 43, in <module>
    from pylint.config.configuration_mixin import ConfigurationMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/configuration_mixin.py", line 4, in <module>
    from pylint.config.option_manager_mixin import OptionsManagerMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/option_manager_mixin.py", line 19, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ grep pylint.checkers.classes.ClassChecker.dot
+ find . -name pylint.checkers.classes.ClassChecker.dot
+ rm -rf pylint.checkers.classes.ClassChecker.dot
+ CHECK_RESULT 0 0 0 'L49: -c No Pass'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='L49: -c No Pass'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ pyreverse --show-ancestors 1 string
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pyreverse", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pyreverse')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 37, in run_pyreverse
    from pylint.pyreverse.main import Run as PyreverseRun
  File "/usr/lib/python3.10/site-packages/pylint/pyreverse/main.py", line 31, in <module>
    from pylint.config import ConfigurationMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/__init__.py", line 43, in <module>
    from pylint.config.configuration_mixin import ConfigurationMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/configuration_mixin.py", line 4, in <module>
    from pylint.config.option_manager_mixin import OptionsManagerMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/option_manager_mixin.py", line 19, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ grep classes.dot
+ find . -name classes.dot
+ rm -rf classes.dot
+ CHECK_RESULT 0 0 0 'L53: --show-ancestors No Pass'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='L53: --show-ancestors No Pass'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ pyreverse -a 1 string
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pyreverse", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pyreverse')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 37, in run_pyreverse
    from pylint.pyreverse.main import Run as PyreverseRun
  File "/usr/lib/python3.10/site-packages/pylint/pyreverse/main.py", line 31, in <module>
    from pylint.config import ConfigurationMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/__init__.py", line 43, in <module>
    from pylint.config.configuration_mixin import ConfigurationMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/configuration_mixin.py", line 4, in <module>
    from pylint.config.option_manager_mixin import OptionsManagerMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/option_manager_mixin.py", line 19, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ find . -name classes.dot
+ grep classes.dot
+ rm -rf classes.dot
+ CHECK_RESULT 0 0 0 'L57: -a No Pass'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='L57: -a No Pass'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ pyreverse --all-ancestors string
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pyreverse", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pyreverse')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 37, in run_pyreverse
    from pylint.pyreverse.main import Run as PyreverseRun
  File "/usr/lib/python3.10/site-packages/pylint/pyreverse/main.py", line 31, in <module>
    from pylint.config import ConfigurationMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/__init__.py", line 43, in <module>
    from pylint.config.configuration_mixin import ConfigurationMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/configuration_mixin.py", line 4, in <module>
    from pylint.config.option_manager_mixin import OptionsManagerMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/option_manager_mixin.py", line 19, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ find . -name classes.dot
+ grep classes.dot
+ rm -rf classes.dot
+ CHECK_RESULT 0 0 0 'L61: --all-ancestors No Pass'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='L61: --all-ancestors No Pass'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ pyreverse -A string
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wrapt 1.14.1 (/usr/lib64/python3.10/site-packages), Requirement.parse('wrapt<1.14,>=1.11'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pyreverse", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.12.2', 'console_scripts', 'pyreverse')())
  File "/usr/lib/python3.10/site-packages/pylint/__init__.py", line 37, in run_pyreverse
    from pylint.pyreverse.main import Run as PyreverseRun
  File "/usr/lib/python3.10/site-packages/pylint/pyreverse/main.py", line 31, in <module>
    from pylint.config import ConfigurationMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/__init__.py", line 43, in <module>
    from pylint.config.configuration_mixin import ConfigurationMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/configuration_mixin.py", line 4, in <module>
    from pylint.config.option_manager_mixin import OptionsManagerMixIn
  File "/usr/lib/python3.10/site-packages/pylint/config/option_manager_mixin.py", line 19, in <module>
    from pylint import utils
  File "/usr/lib/python3.10/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 7, in <module>
    from astroid import nodes
  File "/usr/lib/python3.10/site-packages/astroid/__init__.py", line 51, in <module>
    from astroid.nodes import node_classes, scoped_nodes
  File "/usr/lib/python3.10/site-packages/astroid/nodes/__init__.py", line 27, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/usr/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 50, in <module>
    from astroid.bases import Instance, _infer_stmts
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 551, in <module>
    class Generator(BaseInstance):
  File "/usr/lib/python3.10/site-packages/astroid/bases.py", line 557, in Generator
    special_attributes = lazy_descriptor(objectmodel.GeneratorModel)
  File "/usr/lib/python3.10/site-packages/astroid/util.py", line 29, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/objectmodel.py", line 44, in <module>
    from astroid.manager import AstroidManager
  File "/usr/lib/python3.10/site-packages/astroid/manager.py", line 38, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 27, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/astroid/interpreter/_import/util.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt<1.14,>=1.11' distribution was not found and is required by astroid
+ grep classes.dot
+ find . -name classes.dot
+ rm -rf classes.dot
+ CHECK_RESULT 0 0 0 'L65: -A No Pass'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='L65: -A No Pass'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Nov 21 23:00:15 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Nov 21 23:00:16 2023 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Nov 21 23:00:16 2023 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpx_u824pi ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpx_u824pi
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Nov 21 23:00:27 2023 - INFO  - End to restore the test environment.
