+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ DNF_INSTALL 'dim_tools dim'
+ pkgs='dim_tools dim'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'dim_tools dim' --node 1 --tempfile ''
+ tmpfile2='Last metadata expiration check: 1 day, 4:04:27 ago on Tue 21 Nov 2023 01:49:15 AM CST.
No match for argument: dim_tools
No match for argument: dim
Error: Unable to find a match: dim_tools dim'
+ '[' -z '' ']'
+ tmpfile='Last metadata expiration check: 1 day, 4:04:27 ago on Tue 21 Nov 2023 01:49:15 AM CST.
No match for argument: dim_tools
No match for argument: dim
Error: Unable to find a match: dim_tools dim'
+ modprobe dim_monitor
modprobe: FATAL: Module dim_monitor not found in directory /lib/modules/6.1.19-2.oe2303.riscv64
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Wed Nov 22 05:53:43 2023 - INFO  - Start to run test.
+ gcc ../common/proc/dim_proc.c -o dim_proc
+ gcc ../common/proc/dim_proc_new.c -o dim_proc_new
++ uname -r
++ pwd
+ make -C /lib/modules/6.1.19-2.oe2303.riscv64/build M=/root/mugen/testcases/cli-test/dim/oe_test_dim_measure_002/../common/module modules
make: Entering directory '/root/mugen/testcases/cli-test/dim/oe_test_dim_measure_002'
make: *** /lib/modules/6.1.19-2.oe2303.riscv64/build: No such file or directory.  Stop.
make: Leaving directory '/root/mugen/testcases/cli-test/dim/oe_test_dim_measure_002'
+ mkdir -p /etc/dim/digest_list
+ dim_gen_baseline dim_proc -o /etc/dim/digest_list/dim_proc.hash
oe_test_dim_measure_002.sh: line 32: dim_gen_baseline: command not found
++ uname -r
+ dim_gen_baseline /usr/lib/modules/6.1.19-2.oe2303.riscv64/kernel/drivers/block/kvdo.ko -o /etc/dim/digest_list/kvdo.hash
oe_test_dim_measure_002.sh: line 33: dim_gen_baseline: command not found
++ pwd
+ echo 'measure obj=BPRM_TEXT path=/root/mugen/testcases/cli-test/dim/oe_test_dim_measure_002/dim_proc'
+ echo 'measure obj=MODULE_TEXT name=kvdo'
+ modprobe kvdo
+ ./dim_proc
modprobe: FATAL: Module kvdo not found in directory /lib/modules/6.1.19-2.oe2303.riscv64
+ echo 1
oe_test_dim_measure_002.sh: line 39: /sys/kernel/security/dim/baseline_init: No such file or directory
+ CHECK_RESULT 1 0 0 'baseline_init failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='baseline_init failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'baseline_init failed.'
+ LOG_ERROR 'baseline_init failed.'
+ message='baseline_init failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'baseline_init failed.'
Wed Nov 22 05:53:46 2023 - ERROR - baseline_init failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_dim_measure_002.sh line 40'
+ message='oe_test_dim_measure_002.sh line 40'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_dim_measure_002.sh line 40'
Wed Nov 22 05:53:46 2023 - ERROR - oe_test_dim_measure_002.sh line 40
+ '[' 0 -eq 1 ']'
+ return 0
+ cat /sys/kernel/security/dim/ascii_runtime_measurements
+ grep tampered
cat: /sys/kernel/security/dim/ascii_runtime_measurements: No such file or directory
+ CHECK_RESULT 1 0 1 'get measure log failed.'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='get measure log failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ echo 1
oe_test_dim_measure_002.sh: line 43: /sys/kernel/security/dim/monitor_baseline: No such file or directory
+ CHECK_RESULT 1 0 0 'monitor_baseline failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='monitor_baseline failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'monitor_baseline failed.'
+ LOG_ERROR 'monitor_baseline failed.'
+ message='monitor_baseline failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'monitor_baseline failed.'
Wed Nov 22 05:53:46 2023 - ERROR - monitor_baseline failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_dim_measure_002.sh line 44'
+ message='oe_test_dim_measure_002.sh line 44'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_dim_measure_002.sh line 44'
Wed Nov 22 05:53:47 2023 - ERROR - oe_test_dim_measure_002.sh line 44
+ '[' 0 -eq 1 ']'
+ return 0
+ echo 1
oe_test_dim_measure_002.sh: line 45: /sys/kernel/security/dim/monitor_run: No such file or directory
+ CHECK_RESULT 1 0 0 'monitor_run failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='monitor_run failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'monitor_run failed.'
+ LOG_ERROR 'monitor_run failed.'
+ message='monitor_run failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'monitor_run failed.'
Wed Nov 22 05:53:47 2023 - ERROR - monitor_run failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_dim_measure_002.sh line 46'
+ message='oe_test_dim_measure_002.sh line 46'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_dim_measure_002.sh line 46'
Wed Nov 22 05:53:48 2023 - ERROR - oe_test_dim_measure_002.sh line 46
+ '[' 0 -eq 1 ']'
+ return 0
+ cat /sys/kernel/security/dim/monitor_ascii_runtime_measurements
+ grep tampered
cat: /sys/kernel/security/dim/monitor_ascii_runtime_measurements: No such file or directory
+ CHECK_RESULT 1 0 1 'get monitor log failed.'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='get monitor log failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ pkill -9 dim_proc
oe_test_dim_measure_002.sh: line 24:   966 Killed                  ./dim_proc
+ rmmod kvdo
rmmod: ERROR: Module kvdo is not currently loaded
+ mv dim_proc_new dim_proc
+ insmod ../common/module/kvdo.ko
+ ./dim_proc
insmod: ERROR: could not load module ../common/module/kvdo.ko: No such file or directory
+ echo 1
oe_test_dim_measure_002.sh: line 56: /sys/kernel/security/dim/measure: No such file or directory
+ CHECK_RESULT 1 0 0 'measure failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='measure failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'measure failed.'
+ LOG_ERROR 'measure failed.'
+ message='measure failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'measure failed.'
Wed Nov 22 05:53:48 2023 - ERROR - measure failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_dim_measure_002.sh line 57'
+ message='oe_test_dim_measure_002.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_dim_measure_002.sh line 57'
Wed Nov 22 05:53:49 2023 - ERROR - oe_test_dim_measure_002.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ cat /sys/kernel/security/dim/ascii_runtime_measurements
+ grep tampered
+ grep kvdo
cat: /sys/kernel/security/dim/ascii_runtime_measurements: No such file or directory
+ CHECK_RESULT 1 0 0 'get measure log failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='get measure log failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'get measure log failed.'
+ LOG_ERROR 'get measure log failed.'
+ message='get measure log failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'get measure log failed.'
Wed Nov 22 05:53:49 2023 - ERROR - get measure log failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_dim_measure_002.sh line 59'
+ message='oe_test_dim_measure_002.sh line 59'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_dim_measure_002.sh line 59'
Wed Nov 22 05:53:50 2023 - ERROR - oe_test_dim_measure_002.sh line 59
+ '[' 0 -eq 1 ']'
+ return 0
+ cat /sys/kernel/security/dim/ascii_runtime_measurements
+ grep tampered
+ grep dim_proc
cat: /sys/kernel/security/dim/ascii_runtime_measurements: No such file or directory
+ CHECK_RESULT 1 0 0 'get measure log failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='get measure log failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'get measure log failed.'
+ LOG_ERROR 'get measure log failed.'
+ message='get measure log failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'get measure log failed.'
Wed Nov 22 05:53:50 2023 - ERROR - get measure log failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_dim_measure_002.sh line 61'
+ message='oe_test_dim_measure_002.sh line 61'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_dim_measure_002.sh line 61'
Wed Nov 22 05:53:51 2023 - ERROR - oe_test_dim_measure_002.sh line 61
+ '[' 0 -eq 1 ']'
+ return 0
+ echo 'measure obj=BPRM_TEXT path=/usr/bin/bash'
+ echo 1
oe_test_dim_measure_002.sh: line 64: /sys/kernel/security/dim/baseline_init: No such file or directory
+ CHECK_RESULT 1 0 0 'baseline_init failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='baseline_init failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'baseline_init failed.'
+ LOG_ERROR 'baseline_init failed.'
+ message='baseline_init failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'baseline_init failed.'
Wed Nov 22 05:53:51 2023 - ERROR - baseline_init failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_dim_measure_002.sh line 65'
+ message='oe_test_dim_measure_002.sh line 65'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_dim_measure_002.sh line 65'
Wed Nov 22 05:53:52 2023 - ERROR - oe_test_dim_measure_002.sh line 65
+ '[' 0 -eq 1 ']'
+ return 0
+ echo 1
oe_test_dim_measure_002.sh: line 66: /sys/kernel/security/dim/monitor_run: No such file or directory
+ CHECK_RESULT 1 0 0 'monitor_run failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='monitor_run failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'monitor_run failed.'
+ LOG_ERROR 'monitor_run failed.'
+ message='monitor_run failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'monitor_run failed.'
Wed Nov 22 05:53:52 2023 - ERROR - monitor_run failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_dim_measure_002.sh line 67'
+ message='oe_test_dim_measure_002.sh line 67'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_dim_measure_002.sh line 67'
Wed Nov 22 05:53:53 2023 - ERROR - oe_test_dim_measure_002.sh line 67
+ '[' 0 -eq 1 ']'
+ return 0
+ cat /sys/kernel/security/dim/monitor_ascii_runtime_measurements
+ grep tampered
cat: /sys/kernel/security/dim/monitor_ascii_runtime_measurements: No such file or directory
+ CHECK_RESULT 1 0 0 'get monitor log failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='get monitor log failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'get monitor log failed.'
+ LOG_ERROR 'get monitor log failed.'
+ message='get monitor log failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'get monitor log failed.'
Wed Nov 22 05:53:53 2023 - ERROR - get monitor log failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_dim_measure_002.sh line 69'
+ message='oe_test_dim_measure_002.sh line 69'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_dim_measure_002.sh line 69'
Wed Nov 22 05:53:53 2023 - ERROR - oe_test_dim_measure_002.sh line 69
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End of the test.'
+ message='End of the test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of the test.'
Wed Nov 22 05:53:54 2023 - INFO  - End of the test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 9
+ test 9 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Nov 22 05:53:54 2023 - ERROR - failed to execute the case.
+ exit 9
+ post_test
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z Last metadata expiration check: 1 day, 4:04:27 ago on Tue 21 Nov 2023 01:49:15 AM CST.
No match for argument: dim_tools
No match for argument: dim
Error: Unable to find a match: dim_tools dim ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile 'Last metadata expiration check: 1 day, 4:04:27 ago on Tue 21 Nov 2023 01:49:15 AM CST.
No match for argument: dim_tools
No match for argument: dim
Error: Unable to find a match: dim_tools dim'
Traceback (most recent call last):
  File "/root/mugen/libs/locallibs/rpm_manage.py", line 192, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/mugen/libs/locallibs/rpm_manage.py", line 163, in rpm_remove
    with open(tmpfile, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Last metadata expiration check: 1 day, 4:04:27 ago on Tue 21 Nov 2023 01:49:15 AM CST.\nNo match for argument: dim_tools\nNo match for argument: dim\nError: Unable to find a match: dim_tools dim'
+ '[' 0 -ne 0 ']'
+ pkill -9 dim_proc
oe_test_dim_measure_002.sh: line 74:   981 Killed                  ./dim_proc
+ rmmod kvdo dim_monitor dim_core
rmmod: ERROR: Module kvdo is not currently loaded
rmmod: ERROR: Module dim_monitor is not currently loaded
rmmod: ERROR: Module dim_core is not currently loaded
+ rm -rf /etc/dim/
++ uname -r
++ pwd
+ make -C /lib/modules/6.1.19-2.oe2303.riscv64/build M=/root/mugen/testcases/cli-test/dim/oe_test_dim_measure_002/../common/module clean
make: Entering directory '/root/mugen/testcases/cli-test/dim/oe_test_dim_measure_002'
make: *** /lib/modules/6.1.19-2.oe2303.riscv64/build: No such file or directory.  Stop.
make: Leaving directory '/root/mugen/testcases/cli-test/dim/oe_test_dim_measure_002'
+ rm -rf dim_proc
